// <auto-generated />
namespace Texxtoor.DataModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class localcheck : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(localcheck));
        
        string IMigrationMetadata.Id
        {
            get { return "201501021050587_localcheck"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
