window.localize = window.localize || {};
window.localize.Panes = {
  "Equations_Greek": "Greek",
  "Equations_InsertCustomEquation": "Insert Custom Equation",
  "Equations_Letters": "Letters",
  "Equations_Predefined": "Predefined",
  "Equations_Scripts": "Scripts",
  "Format_Font_Bold": "Bold",
  "Format_Font_Italics": "Italics",
  "Format_Font_NonSemantic": "Font (non semantic)",
  "Format_Font_Sub": "Sub",
  "Format_Font_Sup": "Super",
  "Format_Font_Underline": "Underline",
  "Format_Formatting_Bullets": "Bullets",
  "Format_Formatting_Editing": "Editing",
  "Format_Formatting_Indent": "Indent",
  "Format_Formatting_NonSemantic": "Formatting (non semantic)",
  "Format_Formatting_Numbers": "Numbers",
  "Format_Formatting_Outdent": "Outdent",
  "Format_Formatting_Undo": "Undo",
  "Format_Formatting_RemoveFormat": "Remove Format",
  "Images_Delete": "Delete",
  "Images_DeleteImage": "Delete Image",
  "Images_Insert_Image": "Quick Insert Image",
  "Images_Insert": "Insert Image",
  "Images_Images": "Select Image",
  "Images_Upload": "Upload",
  "Images_Measures": "Measures",
  "Images_Measures_Height": "Height",
  "Images_Measures_Width": "Width",
  "Images_Tools": "Tools",
  "Images_Tools_Colors": "Colors",
  "Images_Tools_Crop": "Crop",
  "Image_Keep_Size": "Keep Size",
  "Listing_Delete": "Delete",
  "Listing_Delete_Listing": "Delete Listing",
  "Listing_Format": "Format",
  "Listing_Format_Code": "Format Code",
  "Listing_Format_FormattingGuide": "Formatting Guide",
  "Listing_Format_LineNumbers": "Line Numbers",
  "Listing_FormattingGuide_Language": "Language",
  "Navigate_Chapters": "Browse Chapters",
  "Navigate_Find": "Find",
  "Navigate_Move_CurrentSection": "Move Current Section",
  "Navigate_Move_Down": "Down",
  "Navigate_Move_HigherLevel": "Higher Level",
  "Navigate_Move_IncludeChildren": "Include Children",
  "Navigate_Move_LowerLevel": "Lower Level",
  "Navigate_Move_Reorganize": "Reorganize",
  "Navigate_Move_Up": "Up",
  "Navigate_Options": "Options",
  "Navigate_Options_ShowFlow": "Show Flow Pane",
  "Navigate_Options_ShowNavi": "Show Quick Navi",
  "Navigate_Options_ShowSematicStyles": "Show Semantic Styles",
  "Navigate_Orphan_IncludeChildren": "Include Children",
  "Navigate_Orphan_Insert_Orphaned": "Insert orphaned snippets",
  "Navigate_Orphan_MergeWithNext": "Merge with Next",
  "Navigate_Orphan_Reorg": "Orphan and Reorganize",
  "Navigate_Orphan_Snippet": "Orphan Snippet",
  "Navigate_Orphane_NoSnippets": "No snippets",
  "Navigate_Replace": "Replace",
  "Navigate_Search": "Search",
  "Navigate_SelectAll": "Select All",
  "Semantic_Insert_Abbreviations": "Abbreviations",
  "Semantic_Insert_Cites": "Cites",
  "Semantic_Insert_Definitions": "Definitions",
  "Semantic_Insert_Elements": "Insert Elements (semantic)",
  "Semantic_Insert_Idiom": "Idiom",
  "Semantic_Insert_Index": "Index",
  "Semantic_Insert_Links": "Links",
  "Semantic_Insert_Variables": "Variables",
  "Semantic_Links": "Links",
  "Semantic_Links_AddInternal": "Add an internal link",
  "Semantic_Links_RemoveLink": "Remove link",
  "Semantic_MetaInformation": "Meta Information",
  "Semantic_MetaInformation_Stage": "Stage",
  "Semantic_MetaInformation_Target": "Target",
  "Semantic_Sidebar": "Sidebar",
  "Semantic_SocialInteraction": "Social Interaction",
  "Semantic_SocialInteraction_Comments": "Comments",
  "Semantic_Text_Elements": "Semantic Text",
  "Semantic_Text_Code": "Code",
  "Semantic_Text_File": "File",
  "Semantic_Text_Keyboard": "Keyboard",
  "Semantic_Type": "Type",
  "Write_Chapter": "Chapter",
  "Write_Clipboard": "Clipboard",
  "Write_Copy": "Copy",
  "Write_Cut": "Cut",
  "Write_Delete": "Delete",
  "Write_Delete_Children": "Delete Children",
  "Write_Delete_Snippet": "Delete Snippet",
  "Write_Insert_Content": "Insert Content",
  "Write_Insert_Content_Listing": "Listing",
  "Write_Insert_Content_Sidebar": "Sidebar",
  "Write_Insert_Content_Text": "Text",
  "Write_Insert_Section": "Insert Section",
  "Write_Paste": "Paste",
  "Write_S1": "1.1 (#1)",
  "Write_S2": "1.1.1 (#2)",
  "Write_S3": "1.1.1.1 (#3)",
  "Write_S4": "1.1.1.1.1 (#4)",
  "Write_ShowWidget_Tab": "Show Widget Tab",
  "Write_ShowWidget_Tab_Equation": "Equation",
  "Write_ShowWidget_Tab_Figure": "Picture",
  "Write_ShowWidget_Tab_Table": "Table",
  "Write_Subsection": "Sub Section",
  "Table_Show_Dimensions": "1. Choose Dimensions",
  "Table_Rows": "Rows",
  "Table_Cols": "Columns",
  "Table_Show_Style": "2. Insert Table with Style",
  "Table_Style_Simple": "Simple",
  "Table_Style_Leading": "Leading Col",
  "Table_Style_Simple_Grid": "Grid",
  "Table_Printer_Settings": "Printer Settings",
  "Table_Repeat_Header": "Repeat Header",
  "Table_Avoid_Page_Break": "Avoid Page Break",
  "Table_Table_Tools": "Table Tools",
  "Table_Insert_Column": "Insert Column",
  "Table_Append_Column": "Append Column",
  "Table_Delete_Column": "Delete Column",
  "Table_Insert_Row": "Insert Row",
  "Table_Append_Row": "Append Row",
  "Table_Delete_Row": "Delete Row",
  "Table_Merge_Cells": "Merge Cells",
  "Table_Split_Cells": "Split Cells",
  "Table_Delete": "Delete",
  "Table_Delete_Table": "Delete Table",
  "Table_Formatting": "Alignment",
  "Table_Formatting_Left": "Left",
  "Table_Formatting_Center": "Center",
  "Table_Formatting_Right": "Right",
  "Table_Formatting_Top": "Top",
  "Table_Formatting_Middle": "Middle",
  "Table_Formatting_Bottom": "Bottom",
  "Review_Trackchanges": "Track Changes",
  "Review_Track": "Tracking",
  "Review_Proofing": "Proofing",
  "Review_Proofing_Spellchecker": "Spellchecker",
  "Review_Proofing_Thesaurus": "Thesaurus"
};