window.localize = window.localize || {};
window.localize.ToolSet = {
  "Orb_Button": "Options",
  "Orb_Actions": "Actions",
  "Orb_Actions_AppendChapter": "Append Chapter",
  "Orb_Actions_GlobalComments": "Document Level Comments",
  "Orb_Actions_Publish": "Go to Publishing",
  "Orb_Close": "Close",
  "Orb_FileDown": "File Download",
  "Orb_HtmlPreview": "Website Preview",
  "Orb_EpubPreview": "EPUB Preview",
  "Orb_PdfPreview": "PDF Preview",
  "Orb_Publish": "Publish Text",
  "Orb_Download": "Download Backup",
  "Orb_Props_CharCount": "Character Count",
  "Orb_Props_DocumentInfo": "Document Information",
  "Orb_Props_Properties": "Properties...",
  "Orb_Props_WordCount": "Word Count",
  "Orb_Toc": "Table of Content",
  "Tab_Create": "INSERT",
  "Tab_Equations": "EQUATIONS",
  "Tab_Figures": "PICTURE",
  "Tab_Format": "HOME",
  "Tab_Listings": "CODE LISTING",
  "Tab_Semantic": "SEMANTIC DATA",
  "Tab_Structure": "DOCUMENT",
  "Tab_Tables": "TABLE",
  "Tab_Review": "REVIEW",
  "Tab_Document": "DOCUMENT"
};