//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texxtoor.DataModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Panes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Panes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Texxtoor.DataModels.EditorResources.Panes", typeof(Panes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string Equations_Greek {
            get {
                return ResourceManager.GetString("Equations_Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Custom Equation.
        /// </summary>
        public static string Equations_InsertCustomEquation {
            get {
                return ResourceManager.GetString("Equations_InsertCustomEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters.
        /// </summary>
        public static string Equations_Letters {
            get {
                return ResourceManager.GetString("Equations_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined.
        /// </summary>
        public static string Equations_Predefined {
            get {
                return ResourceManager.GetString("Equations_Predefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        public static string Equations_Scripts {
            get {
                return ResourceManager.GetString("Equations_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Format_Font_Bold {
            get {
                return ResourceManager.GetString("Format_Font_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italics.
        /// </summary>
        public static string Format_Font_Italics {
            get {
                return ResourceManager.GetString("Format_Font_Italics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font (non semantic).
        /// </summary>
        public static string Format_Font_NonSemantic {
            get {
                return ResourceManager.GetString("Format_Font_NonSemantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub.
        /// </summary>
        public static string Format_Font_Sub {
            get {
                return ResourceManager.GetString("Format_Font_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super.
        /// </summary>
        public static string Format_Font_Sup {
            get {
                return ResourceManager.GetString("Format_Font_Sup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string Format_Font_Underline {
            get {
                return ResourceManager.GetString("Format_Font_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets.
        /// </summary>
        public static string Format_Formatting_Bullets {
            get {
                return ResourceManager.GetString("Format_Formatting_Bullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string Format_Formatting_Editing {
            get {
                return ResourceManager.GetString("Format_Formatting_Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        public static string Format_Formatting_Indent {
            get {
                return ResourceManager.GetString("Format_Formatting_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting (non semantic).
        /// </summary>
        public static string Format_Formatting_NonSemantic {
            get {
                return ResourceManager.GetString("Format_Formatting_NonSemantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string Format_Formatting_Numbers {
            get {
                return ResourceManager.GetString("Format_Formatting_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdent.
        /// </summary>
        public static string Format_Formatting_Outdent {
            get {
                return ResourceManager.GetString("Format_Formatting_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Format_Formatting_Undo {
            get {
                return ResourceManager.GetString("Format_Formatting_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Images_Delete {
            get {
                return ResourceManager.GetString("Images_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image.
        /// </summary>
        public static string Images_DeleteImage {
            get {
                return ResourceManager.GetString("Images_DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        public static string Images_Insert_Image {
            get {
                return ResourceManager.GetString("Images_Insert_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures.
        /// </summary>
        public static string Images_Measures {
            get {
                return ResourceManager.GetString("Images_Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Images_Measures_Height {
            get {
                return ResourceManager.GetString("Images_Measures_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Images_Measures_Width {
            get {
                return ResourceManager.GetString("Images_Measures_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Images_Tools {
            get {
                return ResourceManager.GetString("Images_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Images_Tools_Colors {
            get {
                return ResourceManager.GetString("Images_Tools_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string Images_Tools_Crop {
            get {
                return ResourceManager.GetString("Images_Tools_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Listing_Delete {
            get {
                return ResourceManager.GetString("Listing_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Listing.
        /// </summary>
        public static string Listing_Delete_Listing {
            get {
                return ResourceManager.GetString("Listing_Delete_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Listing_Format {
            get {
                return ResourceManager.GetString("Listing_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Code.
        /// </summary>
        public static string Listing_Format_Code {
            get {
                return ResourceManager.GetString("Listing_Format_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting Guide.
        /// </summary>
        public static string Listing_Format_FormattingGuide {
            get {
                return ResourceManager.GetString("Listing_Format_FormattingGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Numbers.
        /// </summary>
        public static string Listing_Format_LineNumbers {
            get {
                return ResourceManager.GetString("Listing_Format_LineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Listing_FormattingGuide_Language {
            get {
                return ResourceManager.GetString("Listing_FormattingGuide_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Navigate_Find {
            get {
                return ResourceManager.GetString("Navigate_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Current Section.
        /// </summary>
        public static string Navigate_Move_CurrentSection {
            get {
                return ResourceManager.GetString("Navigate_Move_CurrentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Navigate_Move_Down {
            get {
                return ResourceManager.GetString("Navigate_Move_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher Level.
        /// </summary>
        public static string Navigate_Move_HigherLevel {
            get {
                return ResourceManager.GetString("Navigate_Move_HigherLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Children.
        /// </summary>
        public static string Navigate_Move_IncludeChildren {
            get {
                return ResourceManager.GetString("Navigate_Move_IncludeChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Level.
        /// </summary>
        public static string Navigate_Move_LowerLevel {
            get {
                return ResourceManager.GetString("Navigate_Move_LowerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorganize.
        /// </summary>
        public static string Navigate_Move_Reorganize {
            get {
                return ResourceManager.GetString("Navigate_Move_Reorganize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Navigate_Move_Up {
            get {
                return ResourceManager.GetString("Navigate_Move_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Navigate_Options {
            get {
                return ResourceManager.GetString("Navigate_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Flow Pane.
        /// </summary>
        public static string Navigate_Options_ShowFlow {
            get {
                return ResourceManager.GetString("Navigate_Options_ShowFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Quick Navi.
        /// </summary>
        public static string Navigate_Options_ShowNavi {
            get {
                return ResourceManager.GetString("Navigate_Options_ShowNavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Semantic Styles.
        /// </summary>
        public static string Navigate_Options_ShowSematicStyles {
            get {
                return ResourceManager.GetString("Navigate_Options_ShowSematicStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Children.
        /// </summary>
        public static string Navigate_Orphan_IncludeChildren {
            get {
                return ResourceManager.GetString("Navigate_Orphan_IncludeChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert orphaned snippets.
        /// </summary>
        public static string Navigate_Orphan_Insert_Orphaned {
            get {
                return ResourceManager.GetString("Navigate_Orphan_Insert_Orphaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge with Next.
        /// </summary>
        public static string Navigate_Orphan_MergeWithNext {
            get {
                return ResourceManager.GetString("Navigate_Orphan_MergeWithNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphan and Reorganize.
        /// </summary>
        public static string Navigate_Orphan_Reorg {
            get {
                return ResourceManager.GetString("Navigate_Orphan_Reorg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphan Snippet.
        /// </summary>
        public static string Navigate_Orphan_Snippet {
            get {
                return ResourceManager.GetString("Navigate_Orphan_Snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No snippets.
        /// </summary>
        public static string Navigate_Orphane_NoSnippets {
            get {
                return ResourceManager.GetString("Navigate_Orphane_NoSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Navigate_Replace {
            get {
                return ResourceManager.GetString("Navigate_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Navigate_Search {
            get {
                return ResourceManager.GetString("Navigate_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Navigate_SelectAll {
            get {
                return ResourceManager.GetString("Navigate_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviations.
        /// </summary>
        public static string Semantic_Insert_Abbreviations {
            get {
                return ResourceManager.GetString("Semantic_Insert_Abbreviations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cites.
        /// </summary>
        public static string Semantic_Insert_Cites {
            get {
                return ResourceManager.GetString("Semantic_Insert_Cites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string Semantic_Insert_Definitions {
            get {
                return ResourceManager.GetString("Semantic_Insert_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Elements (semantic).
        /// </summary>
        public static string Semantic_Insert_Elements {
            get {
                return ResourceManager.GetString("Semantic_Insert_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiom.
        /// </summary>
        public static string Semantic_Insert_Idiom {
            get {
                return ResourceManager.GetString("Semantic_Insert_Idiom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Semantic_Insert_Index {
            get {
                return ResourceManager.GetString("Semantic_Insert_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Semantic_Insert_Links {
            get {
                return ResourceManager.GetString("Semantic_Insert_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string Semantic_Insert_Variables {
            get {
                return ResourceManager.GetString("Semantic_Insert_Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Semantic_Links {
            get {
                return ResourceManager.GetString("Semantic_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an internal link.
        /// </summary>
        public static string Semantic_Links_AddInternal {
            get {
                return ResourceManager.GetString("Semantic_Links_AddInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove link.
        /// </summary>
        public static string Semantic_Links_RemoveLink {
            get {
                return ResourceManager.GetString("Semantic_Links_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Information.
        /// </summary>
        public static string Semantic_MetaInformation {
            get {
                return ResourceManager.GetString("Semantic_MetaInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Semantic_MetaInformation_Stage {
            get {
                return ResourceManager.GetString("Semantic_MetaInformation_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Semantic_MetaInformation_Target {
            get {
                return ResourceManager.GetString("Semantic_MetaInformation_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar.
        /// </summary>
        public static string Semantic_Sidebar {
            get {
                return ResourceManager.GetString("Semantic_Sidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Interaction.
        /// </summary>
        public static string Semantic_SocialInteraction {
            get {
                return ResourceManager.GetString("Semantic_SocialInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Semantic_SocialInteraction_Comments {
            get {
                return ResourceManager.GetString("Semantic_SocialInteraction_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Semantic_Type {
            get {
                return ResourceManager.GetString("Semantic_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append Column.
        /// </summary>
        public static string Table_AppendCol {
            get {
                return ResourceManager.GetString("Table_AppendCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append Row.
        /// </summary>
        public static string Table_AppendRow {
            get {
                return ResourceManager.GetString("Table_AppendRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid Page Break.
        /// </summary>
        public static string Table_AvoidPageBreak {
            get {
                return ResourceManager.GetString("Table_AvoidPageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Choose Dimensions.
        /// </summary>
        public static string Table_Choose_Dimensions {
            get {
                return ResourceManager.GetString("Table_Choose_Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Insert Table with Style.
        /// </summary>
        public static string Table_Choose_Style {
            get {
                return ResourceManager.GetString("Table_Choose_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Table_Delete {
            get {
                return ResourceManager.GetString("Table_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Column.
        /// </summary>
        public static string Table_DeleteCol {
            get {
                return ResourceManager.GetString("Table_DeleteCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string Table_DeleteRow {
            get {
                return ResourceManager.GetString("Table_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Table.
        /// </summary>
        public static string Table_DeleteTable {
            get {
                return ResourceManager.GetString("Table_DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Column.
        /// </summary>
        public static string Table_InsertCol {
            get {
                return ResourceManager.GetString("Table_InsertCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Row.
        /// </summary>
        public static string Table_InsertRow {
            get {
                return ResourceManager.GetString("Table_InsertRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Cells.
        /// </summary>
        public static string Table_MergeCells {
            get {
                return ResourceManager.GetString("Table_MergeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Settings.
        /// </summary>
        public static string Table_Printer_Settings {
            get {
                return ResourceManager.GetString("Table_Printer_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Header.
        /// </summary>
        public static string Table_RepeatHeader {
            get {
                return ResourceManager.GetString("Table_RepeatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Cells.
        /// </summary>
        public static string Table_SplitCells {
            get {
                return ResourceManager.GetString("Table_SplitCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Tools.
        /// </summary>
        public static string Table_Tools {
            get {
                return ResourceManager.GetString("Table_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        public static string Write_Chapter {
            get {
                return ResourceManager.GetString("Write_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Write_Clipboard {
            get {
                return ResourceManager.GetString("Write_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Write_Copy {
            get {
                return ResourceManager.GetString("Write_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Write_Cut {
            get {
                return ResourceManager.GetString("Write_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Write_Delete {
            get {
                return ResourceManager.GetString("Write_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Children.
        /// </summary>
        public static string Write_Delete_Children {
            get {
                return ResourceManager.GetString("Write_Delete_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Snippet.
        /// </summary>
        public static string Write_Delete_Snippet {
            get {
                return ResourceManager.GetString("Write_Delete_Snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Content.
        /// </summary>
        public static string Write_Insert_Content {
            get {
                return ResourceManager.GetString("Write_Insert_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        public static string Write_Insert_Content_Listing {
            get {
                return ResourceManager.GetString("Write_Insert_Content_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar.
        /// </summary>
        public static string Write_Insert_Content_Sidebar {
            get {
                return ResourceManager.GetString("Write_Insert_Content_Sidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Write_Insert_Content_Text {
            get {
                return ResourceManager.GetString("Write_Insert_Content_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Section.
        /// </summary>
        public static string Write_Insert_Section {
            get {
                return ResourceManager.GetString("Write_Insert_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Write_Paste {
            get {
                return ResourceManager.GetString("Write_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1 (#1).
        /// </summary>
        public static string Write_S1 {
            get {
                return ResourceManager.GetString("Write_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.1 (#2).
        /// </summary>
        public static string Write_S2 {
            get {
                return ResourceManager.GetString("Write_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.1.1 (#3).
        /// </summary>
        public static string Write_S3 {
            get {
                return ResourceManager.GetString("Write_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.1.1.1 (#4).
        /// </summary>
        public static string Write_S4 {
            get {
                return ResourceManager.GetString("Write_S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Widget Tab.
        /// </summary>
        public static string Write_ShowWidget_Tab {
            get {
                return ResourceManager.GetString("Write_ShowWidget_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equation.
        /// </summary>
        public static string Write_ShowWidget_Tab_Equation {
            get {
                return ResourceManager.GetString("Write_ShowWidget_Tab_Equation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure.
        /// </summary>
        public static string Write_ShowWidget_Tab_Figure {
            get {
                return ResourceManager.GetString("Write_ShowWidget_Tab_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Write_ShowWidget_Tab_Table {
            get {
                return ResourceManager.GetString("Write_ShowWidget_Tab_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Section.
        /// </summary>
        public static string Write_Subsection {
            get {
                return ResourceManager.GetString("Write_Subsection", resourceCulture);
            }
        }
    }
}
