//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texxtoor.DataModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolSet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolSet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Texxtoor.DataModels.EditorResources.ToolSet", typeof(ToolSet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Orb_Actions {
            get {
                return ResourceManager.GetString("Orb_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append Chapter.
        /// </summary>
        public static string Orb_Actions_AppendChapter {
            get {
                return ResourceManager.GetString("Orb_Actions_AppendChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Orb_Actions_Publish {
            get {
                return ResourceManager.GetString("Orb_Actions_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Copy.
        /// </summary>
        public static string Orb_Backup {
            get {
                return ResourceManager.GetString("Orb_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Orb_Close {
            get {
                return ResourceManager.GetString("Orb_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Orb_Export {
            get {
                return ResourceManager.GetString("Orb_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Orb_Online {
            get {
                return ResourceManager.GetString("Orb_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Preview.
        /// </summary>
        public static string Orb_ProductionInfo {
            get {
                return ResourceManager.GetString("Orb_ProductionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Count.
        /// </summary>
        public static string Orb_Props_CharCount {
            get {
                return ResourceManager.GetString("Orb_Props_CharCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Information.
        /// </summary>
        public static string Orb_Props_DocumentInfo {
            get {
                return ResourceManager.GetString("Orb_Props_DocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties....
        /// </summary>
        public static string Orb_Props_Properties {
            get {
                return ResourceManager.GetString("Orb_Props_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count.
        /// </summary>
        public static string Orb_Props_WordCount {
            get {
                return ResourceManager.GetString("Orb_Props_WordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of Content.
        /// </summary>
        public static string Orb_Toc {
            get {
                return ResourceManager.GetString("Orb_Toc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Tab_Create {
            get {
                return ResourceManager.GetString("Tab_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equations.
        /// </summary>
        public static string Tab_Equations {
            get {
                return ResourceManager.GetString("Tab_Equations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figures.
        /// </summary>
        public static string Tab_Figures {
            get {
                return ResourceManager.GetString("Tab_Figures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Tab_Format {
            get {
                return ResourceManager.GetString("Tab_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listings.
        /// </summary>
        public static string Tab_Listings {
            get {
                return ResourceManager.GetString("Tab_Listings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic.
        /// </summary>
        public static string Tab_Semantic {
            get {
                return ResourceManager.GetString("Tab_Semantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure.
        /// </summary>
        public static string Tab_Structure {
            get {
                return ResourceManager.GetString("Tab_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tab_Tables {
            get {
                return ResourceManager.GetString("Tab_Tables", resourceCulture);
            }
        }
    }
}
