//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texxtoor.DataModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Widgets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Widgets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Texxtoor.DataModels.EditorResources.Widgets", typeof(Widgets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure.
        /// </summary>
        public static string Image_Figure {
            get {
                return ResourceManager.GetString("Image_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel &amp; Close.
        /// </summary>
        public static string Image_Tools_Btn_Cancel {
            get {
                return ResourceManager.GetString("Image_Tools_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Image_Tools_Btn_Ok {
            get {
                return ResourceManager.GetString("Image_Tools_Btn_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Image_Tools_Btn_Preview {
            get {
                return ResourceManager.GetString("Image_Tools_Btn_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Image.
        /// </summary>
        public static string Image_Tools_Crop_Image {
            get {
                return ResourceManager.GetString("Image_Tools_Crop_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep ratio.
        /// </summary>
        public static string Image_Tools_Crop_KeepRatio {
            get {
                return ResourceManager.GetString("Image_Tools_Crop_KeepRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Image_Tools_Crop_None {
            get {
                return ResourceManager.GetString("Image_Tools_Crop_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set ratio.
        /// </summary>
        public static string Image_Tools_Crop_Set_Ratio {
            get {
                return ResourceManager.GetString("Image_Tools_Crop_Set_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop size.
        /// </summary>
        public static string Image_Tools_Crop_Size {
            get {
                return ResourceManager.GetString("Image_Tools_Crop_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Image_Tools_Image_Brightness {
            get {
                return ResourceManager.GetString("Image_Tools_Image_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Colors.
        /// </summary>
        public static string Image_Tools_Image_Colors {
            get {
                return ResourceManager.GetString("Image_Tools_Image_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string Image_Tools_Image_Contrast {
            get {
                return ResourceManager.GetString("Image_Tools_Image_Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        public static string Image_Tools_Image_Hue {
            get {
                return ResourceManager.GetString("Image_Tools_Image_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string Image_Tools_Image_Saturation {
            get {
                return ResourceManager.GetString("Image_Tools_Image_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent Color.
        /// </summary>
        public static string Image_Tools_Transparent_Colors {
            get {
                return ResourceManager.GetString("Image_Tools_Transparent_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images.
        /// </summary>
        public static string Image_Tools_Upload {
            get {
                return ResourceManager.GetString("Image_Tools_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string InternalLink_Tool_Caption {
            get {
                return ResourceManager.GetString("InternalLink_Tool_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Links.
        /// </summary>
        public static string InternalLink_Tool_Internal_Links {
            get {
                return ResourceManager.GetString("InternalLink_Tool_Internal_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an element that hyperlinks to a place inside this book..
        /// </summary>
        public static string InternalLink_Tool_Text {
            get {
                return ResourceManager.GetString("InternalLink_Tool_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        public static string Listing_Listing {
            get {
                return ResourceManager.GetString("Listing_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can append chapters.
        /// </summary>
        public static string Properties_AllowChapters_Label {
            get {
                return ResourceManager.GetString("Properties_AllowChapters_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can use Meta Data for elements.
        /// </summary>
        public static string Properties_AllowMetadata_Label {
            get {
                return ResourceManager.GetString("Properties_AllowMetadata_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string Properties_Defaults {
            get {
                return ResourceManager.GetString("Properties_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Title.
        /// </summary>
        public static string Properties_Defaults_ChapterTitle {
            get {
                return ResourceManager.GetString("Properties_Defaults_ChapterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        public static string Properties_Defaults_Listing {
            get {
                return ResourceManager.GetString("Properties_Defaults_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Title.
        /// </summary>
        public static string Properties_Defaults_SectionTitle {
            get {
                return ResourceManager.GetString("Properties_Defaults_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Properties_Defaults_Text {
            get {
                return ResourceManager.GetString("Properties_Defaults_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Properties.
        /// </summary>
        public static string Properties_Document_Properties {
            get {
                return ResourceManager.GetString("Properties_Document_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Functions.
        /// </summary>
        public static string Properties_Legend {
            get {
                return ResourceManager.GetString("Properties_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Functions.
        /// </summary>
        public static string Properties_ShowFunctions {
            get {
                return ResourceManager.GetString("Properties_ShowFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar with element symbols (left).
        /// </summary>
        public static string Properties_ShowFunctions_FlowPane {
            get {
                return ResourceManager.GetString("Properties_ShowFunctions_FlowPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar with navigation elements (right).
        /// </summary>
        public static string Properties_ShowFunctions_NaviPane {
            get {
                return ResourceManager.GetString("Properties_ShowFunctions_NaviPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows properties that apply to this document while editing..
        /// </summary>
        public static string Properties_Text {
            get {
                return ResourceManager.GetString("Properties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior of presentation.
        /// </summary>
        public static string Propertires_Behavior_Legend {
            get {
                return ResourceManager.GetString("Propertires_Behavior_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section appear with 1., 1.1., 1.1.1 (otherwise #1, #2, #3 and so on).
        /// </summary>
        public static string Propertires_Behavior_ShowNumberChain {
            get {
                return ResourceManager.GetString("Propertires_Behavior_ShowNumberChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List is empty.
        /// </summary>
        public static string Semantic_Empty {
            get {
                return ResourceManager.GetString("Semantic_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table_Table {
            get {
                return ResourceManager.GetString("Table_Table", resourceCulture);
            }
        }
    }
}
