window.localize = window.localize || {};
window.localize.Panes = {
  "Document_Engine": "Anbieter",
  "Document_Engine_Bing": "Bing",
  "Document_Engine_Google": "Google",
  "Document_Options": "Optionen",
  "Document_AutoTrans": "Automatische Übersetzung",
  "Format_Font_Bold": "Fett",
  "Format_Font_Italics": "Kursiv",
  "Format_Font_NonSemantic": "Font (nicht semantisch)",
  "Format_Font_Sub": "Runter",
  "Format_Font_Sup": "Hoch",
  "Format_Font_Underline": "Unterstreichen",
  "Format_Formatting_Bullets": "Aufzählung",
  "Format_Formatting_Editing": "Bearbeiten",
  "Format_Formatting_Indent": "Einrücken",
  "Format_Formatting_NonSemantic": "Formatierung (nicht semantisch)",
  "Format_Formatting_Numbers": "Zahlen",
  "Format_Formatting_Outdent": "Ausrücken",
  "Format_Formatting_Undo": "Undo",
  "Format_Formatting_RemoveFormat": "Format entfernen",
  "Images_Delete": "Löschen",
  "Images_DeleteImage": "Abbildung Löschen",
  "Images_Insert_Image": "Schnelles Einfügen",
  "Images_Insert": "Abbildung einfügen",
  "Images_Images": "Abbildung wählen",
  "Images_Upload": "Hochladen",
  "Images_Measures": "Abmessungen",
  "Images_Measures_Height": "Höhe",
  "Images_Measures_Width": "Breite",
  "Images_Tools": "Werkzeuge",
  "Images_Tools_Colors": "Farben",
  "Images_Tools_Crop": "Beschneiden",
  "Image_Keep_Size": "Originalgröße",
  "Navigate_Find": "Finden",
  "Navigate_Replace": "Ersetzen",
  "Navigate_Search": "Suchen",
  "Navigate_SelectAll": "Alles auswählen",
  "Semantic_Insert_Abbreviations": "Abkürzungen",
  "Semantic_Insert_Cites": "Zitate",
  "Semantic_Insert_Definitions": "Definitionen",
  "Semantic_Insert_Elements": "Elemente (semantisch)",
  "Semantic_Insert_Idiom": "Idiome",
  "Semantic_Insert_Index": "Index",
  "Semantic_Insert_Links": "Links",
  "Semantic_Insert_Variables": "Variablen",
  "Semantic_Links": "Links",
  "Semantic_Links_AddInternal": "Internen Link hinzufügen",
  "Semantic_Links_RemoveLink": "Link entfernen",
  "Semantic_MetaInformation": "Meta-Informationen",
  "Semantic_MetaInformation_Stage": "Niveau",
  "Semantic_MetaInformation_Target": "Zielgruppe",
  "Semantic_Sidebar": "Sidebar",
  "Semantic_SocialInteraction": "Soziale Interaktion",
  "Semantic_SocialInteraction_Comments": "Kommentare",
  "Semantic_Text_Elements": "Semantischer Text",
  "Semantic_Text_Code": "Code",
  "Semantic_Text_File": "Datei",
  "Semantic_Text_Keyboard": "Taste",
  "Semantic_Type": "Typ",
  "Write_Chapter": "Kapitel",
  "Write_Clipboard": "Zwischenablage",
  "Write_Copy": "Kopieren",
  "Write_Cut": "Ausschneiden",
};