window.localize = window.localize || {};
window.localize.Panes = {
  "Equations_Greek": "Griechisch",
  "Equations_InsertCustomEquation": "Eigene Formel",
  "Equations_Letters": "Buchstaben",
  "Equations_Predefined": "Vordefiniert",
  "Equations_Scripts": "Skript",
  "Format_Font_Bold": "Fett",
  "Format_Font_Italics": "Kursiv",
  "Format_Font_NonSemantic": "Font (nicht semantisch)",
  "Format_Font_Sub": "Runter",
  "Format_Font_Sup": "Hoch",
  "Format_Font_Underline": "Unterstreichen",
  "Format_Formatting_Bullets": "Aufzählung",
  "Format_Formatting_Editing": "Bearbeiten",
  "Format_Formatting_Indent": "Einrücken",
  "Format_Formatting_NonSemantic": "Formatierung (nicht semantisch)",
  "Format_Formatting_Numbers": "Zahlen",
  "Format_Formatting_Outdent": "Ausrücken",
  "Format_Formatting_Undo": "Undo",
  "Format_Formatting_RemoveFormat": "Format entfernen",
  "Images_Delete": "Löschen",
  "Images_DeleteImage": "Abbildung Löschen",
  "Images_Insert_Image": "Schnelles Einfügen",
  "Images_Insert": "Abbildung einfügen",
  "Images_Images": "Abbildung wählen",
  "Images_Upload": "Hochladen",
  "Images_Measures": "Abmessungen",
  "Images_Measures_Height": "Höhe",
  "Images_Measures_Width": "Breite",
  "Images_Tools": "Werkzeuge",
  "Images_Tools_Colors": "Farben",
  "Images_Tools_Crop": "Beschneiden",
  "Image_Keep_Size": "Originalgröße",
  "Listing_Delete": "Löschen",
  "Listing_Delete_Listing": "Listing löschen",
  "Listing_Format": "Formatieren",
  "Listing_Format_Code": "Code Formatieren",
  "Listing_Format_FormattingGuide": "Formatierhilfe",
  "Listing_Format_LineNumbers": "Zeilennummern",
  "Listing_FormattingGuide_Language": "Programmiersprache",
  "Navigate_Chapters": "Kapitel wählen",
  "Navigate_Find": "Suchen",
  "Navigate_Move_CurrentSection": "Abschnitt verschieben",
  "Navigate_Move_Down": "Runter",
  "Navigate_Move_HigherLevel": "Höheres Stufe",
  "Navigate_Move_IncludeChildren": "Mit Kindelementen",
  "Navigate_Move_LowerLevel": "Tiefere Stufe",
  "Navigate_Move_Reorganize": "Neu anordnen",
  "Navigate_Move_Up": "Hoch",
  "Navigate_Options": "Optionen",
  "Navigate_Options_ShowFlow": "Zeige Elementleiste",
  "Navigate_Options_ShowNavi": "Zeige Navileiste",
  "Navigate_Options_ShowSematicStyles": "Zeige semantische Stile",
  "Navigate_Orphan_IncludeChildren": "Mit Kindelementen",
  "Navigate_Orphan_Insert_Orphaned": "Zurückgelegte Abschnitte einfügen",
  "Navigate_Orphan_MergeWithNext": "Mit nächstem verbinden",
  "Navigate_Orphan_Reorg": "Zurücklegen und Reorganisieren",
  "Navigate_Orphan_Snippet": "Zurücklegen",
  "Navigate_Orphane_NoSnippets": "Keine Elemente",
  "Navigate_Replace": "Ersetzen",
  "Navigate_Search": "Suchen",
  "Navigate_SelectAll": "Alles auswählen",
  "Semantic_Insert_Abbreviations": "Abkürzungen",
  "Semantic_Insert_Cites": "Zitate",
  "Semantic_Insert_Definitions": "Definitionen",
  "Semantic_Insert_Elements": "Elemente (semantisch)",
  "Semantic_Insert_Idiom": "Idiome",
  "Semantic_Insert_Index": "Index",
  "Semantic_Insert_Links": "Links",
  "Semantic_Insert_Variables": "Variablen",
  "Semantic_Links": "Links",
  "Semantic_Links_AddInternal": "Internen Link hinzufügen",
  "Semantic_Links_RemoveLink": "Link entfernen",
  "Semantic_MetaInformation": "Meta-Informationen",
  "Semantic_MetaInformation_Stage": "Niveau",
  "Semantic_MetaInformation_Target": "Zielgruppe",
  "Semantic_Sidebar": "Sidebar",
  "Semantic_SocialInteraction": "Soziale Interaktion",
  "Semantic_SocialInteraction_Comments": "Kommentare",
  "Semantic_Text_Elements": "Semantischer Text",
  "Semantic_Text_Code": "Code",
  "Semantic_Text_File": "Datei",
  "Semantic_Text_Keyboard": "Taste",
  "Semantic_Type": "Typ",
  "Write_Chapter": "Kapitel",
  "Write_Clipboard": "Zwischenablage",
  "Write_Copy": "Kopieren",
  "Write_Cut": "Ausschneiden",
  "Write_Delete": "Löschen",
  "Write_Delete_Children": "Kindelemente löschen",
  "Write_Delete_Snippet": "Snippet löschen",
  "Write_Insert_Content": "Inhalt einfügen",
  "Write_Insert_Content_Listing": "Listing",
  "Write_Insert_Content_Sidebar": "Sidebar",
  "Write_Insert_Content_Text": "Text",
  "Write_Insert_Section": "Abschnitt einfügen",
  "Write_Paste": "Einfügen",
  "Write_S1": "1.1 (#1)",
  "Write_S2": "1.1.1 (#2)",
  "Write_S3": "1.1.1.1 (#3)",
  "Write_S4": "1.1.1.1.1 (#4)",
  "Write_ShowWidget_Tab": "Zeige Tabs",
  "Write_ShowWidget_Tab_Equation": "Formel",
  "Write_ShowWidget_Tab_Figure": "Abbildung",
  "Write_ShowWidget_Tab_Table": "Tabelle",
  "Write_Subsection": "Unterabschnitt",
  "Table_Show_Dimensions": "1. Maße wählen",
  "Table_Rows": "Reihen",
  "Table_Cols": "Spalten",
  "Table_Show_Style": "2. Tabelle mit Stil einfügen",
  "Table_Style_Simple": "Einfach",
  "Table_Style_Leading": "Führende Spalte",
  "Table_Style_Simple_Grid": "Gitter",
  "Table_Printer_Settings": "Druckeinstellungen",
  "Table_Repeat_Header": "Kopfzeile wiederholen",
  "Table_Avoid_Page_Break": "Seitenumbruch vermeiden",
  "Table_Table_Tools": "Tabellenwerkzeuge",
  "Table_Insert_Column": "Spalte einfügen",
  "Table_Append_Column": "Spalte anhängen",
  "Table_Delete_Column": "Spalte löschen",
  "Table_Insert_Row": "Reihe einfügen",
  "Table_Append_Row": "Reihe anhängen",
  "Table_Delete_Row": "Reihe löschen",
  "Table_Merge_Cells": "Zellen verbinden",
  "Table_Split_Cells": "Zellen teilen",
  "Table_Delete": "Löschen",
  "Table_Delete_Table": "Lösche Tabelle",
  "Table_Formatting": "Ausrichten",
  "Table_Formatting_Left": "Links",
  "Table_Formatting_Center": "Zentriert",
  "Table_Formatting_Right": "Rechts",
  "Table_Formatting_Top": "Oben",
  "Table_Formatting_Middle": "Mitte",
  "Table_Formatting_Bottom": "Unten",
  "Review_Trackchanges": "Track Changes",
  "Review_Track": "Überarbeiten",
  "Review_Proofing": "Korrektur",
  "Review_Proofing_Spellchecker": "Rechtschreibung",
  "Review_Proofing_Thesaurus": "Thesaurus"
};