window.localize = window.localize || {};
window.localize.Widgets = {
  "Image_Figure": "Abbildung",
  "Image_Tools_Btn_Cancel": "Abbrechen & Schließen",
  "Image_Tools_Btn_Ok": "Speichern",
  "Image_Tools_Btn_Preview": "Vorschau",
  "Image_Tools_Btn_Reset": "Zurücksetzen",
  "Image_Tools_Crop_Image": "Beschneiden",
  "Image_Tools_Crop_Text": "Erstelle einen Ausschnitt aus dem Original-Bild. Dies kann rückgängig gemacht werden, das Original bleibt erhalten.",
  "Image_Tools_Crop_KeepRatio": "Verhältnis behalten",
  "Image_Tools_Crop_None": "Keine",
  "Image_Tools_Crop_Set_Ratio": "Verhältnis bestimmen",
  "Image_Tools_Crop_Size": "Zuschnittgröße",
  "Image_Tools_Crop_Position": "Position und Dimension",
  "Image_Tools_Image_Brightness": "Helligkeit",
  "Image_Tools_Image_Colors": "Farben",
  "Image_Tools_Image_Contrast": "Kontrast",
  "Image_Tools_Image_Hue": "Farbton",
  "Image_Tools_Image_Saturation": "Sättigung",
  "Image_Tools_Transparent_Colors": "Transparente Farbe",
  "Image_Tools_Picker_Text": "Select an image to create a figure at the current position. Click on an image to see it in full resolution.",
  "InternalLink_Tool_Caption": "Bezeichnung",
  "InternalLink_Tool_Internal_Links": "Interne Links",
  "InternalLink_Tool_Search": "Suchen",
  "InternalLink_Tool_Text": "Wähle ein Element innerhalb des Textes, auf das verwiesen wird.",
  "Listing_Listing": "Listing",
  "Properties_AllowChapters_Label": "Benutzer kann Kapitel erstellen",
  "Properties_AllowMetadata_Label": "Benutzer kann Meta-Daten für Elemente bestimmen",
  "Properties_Defaults": "Standardwerte",
  "Properties_Defaults_ChapterTitle": "Kapiteltitel",
  "Properties_Defaults_Listing": "Listinginhalt",
  "Properties_Defaults_SectionTitle": "Abschnittstitel",
  "Properties_Defaults_Text": "Textblock",
  "Properties_Document_Properties": "Dokumenteigenschaften",
  "Properties_Legend": "Erlaube Funktionen",
  "Properties_ShowFunctions": "Zeige Funktionen",
  "Properties_ShowFunctions_FlowPane": "Bereich mit Elementsymbolen (links)",
  "Properties_ShowFunctions_NaviPane": "Bereich mit Navigationssymbolen (rechts)",
  "Properties_Text": "Shows properties that apply to this document while editing.",
  "Propertires_Behavior_Legend": "Anzeigeverhalten",
  "Propertires_Behavior_ShowNumberChain": "Abschnitte beginnen mit 1., 1.1., 1.1.1 (sonst #1, #2, #3 usw.)",
  "Semantic_Empty": "Liste ist leer",
  "Table_Table": "Tabelle",
  "Comments_Document_Text": "Kommentare ermöglichen die Kommunikation mit Partnern und Nutzern<br/>Meta-Daten helfen Nutzern, relevante Inhalte zu finden.",
  "Comments_Document_Me": "Private Kommentare",
  "Comments_Document_Team": "Kommentare des Teams",
  "Comments_Document_Reader": "Leserkommentare",
  "Comments_Tools_Btn_Add": "Kommentar hinzufügen",
  "Comments_Tools_Btn_Cancel": "Schließen",
  "Comments_Me_Comments_Add": "Füge einen neuen Kommentar ein. Betreff: ",
  "Comments_Me_Comments_Existing": "Deine privaten Kommentare:",
  "Comments_Team_Comments_Add": "Schreibe deinen Mitstreitern. Betreff: ",
  "Comments_Team_Comments_Existing": "Kommentare deines Teams:",
  "Comments_Reader_Comments_Add": "Antworte deinen Lesern hier. Betreff: ",
  "Comments_Reader_Comments_Existing": "Kommentare deiner Leser:",
  "Comments_MetaData": "Meta-Daten",
  "Comments_MetaData_Hint":"Meta-Daten für Textelemente unterstützen die Matrix-Suche.",
  "Comments_MetaData_Btn_Save": "Speichern",
  "Comments_Reader_Close_Thread": "Diskussion beenden",
  "Upload_Title_Text": "Lade Bilder in das lokale Repository des Projekts und füge (optional) gleich ein Bild ein.",
  "Upload_Title": "Bild hochladen",
  "Upload_Legend_Upload": "Dateien auswählen...",
  "Upload_Button_Add": "Datei hinzufügen",
  "Upload_Error_Common": "Fehler beim hochladen. Bitte versuche es noch einmal.",
  "Upload_Error_MaxFileSize": "Die maximale Dateigröße wurde überschritten (50 MB).",
  "Upload_Error_MinFileSize": "Die Datei ist zu klein für ein Bild (100 Byte).",
  "Upload_Error_FileTypes": "Dieser Dateityp ist nicht erlaubt.",
  "Upload_Error_MaxNumber": "Die maximale Anzahl Dateien wurde erreicht (20).",
  "Upload_Error_EmptyResult": "Es wurde nichts empfangen. Bitte versuche es noch einmal.",
  "Upload_Error_Bytes": "Fehler beim Lesen der Daten. Bitte versuche es noch einmal.",
  "Upload_Error_1": "Die maximale Dateigröße wurde überschritten (50 MB).",
  "Upload_Error_2": "Die maximale Dateigröße wurde überschritten (50 MB).",
  "Upload_Error_3": "Es kontne nur ein Teil hochgeladen werden.",
  "Upload_Error_4": "Es wúrde nichts hochgeladen.",
  "Upload_Error_5": "Server falsch konfiguriert.",
  "Upload_Error_6": "Konnte Daten nicht schreiben.",
  "Upload_Error_7": "Eine Erweiterung verhinderte die Aktion.",
  "Upload_Button_Ok": "OK",
  "Upload_Button_Cancel": "Abbrechen & Schließen",
  "Reorganize_Tools_Btn_Cancel": "Schließen",
  "Reorganize_Tools_Btn_Undo": "Rückgängig & Schließen",
  "Reorganize_Text": "Reorganisiere die Hierarchie der Inhalte im Text. Ziehe Element zu neuen Positionen. Änderungen werden sofort gespeichert."
};