window.localize = window.localize || {};
window.localize.Widgets = {
  "Image_Figure": "Figure",
  "Image_Tools_Btn_Cancel": "Cancel & Close",
  "Image_Tools_Btn_Ok": "Save",
  "Image_Tools_Btn_Preview": "Preview",
  "Image_Tools_Btn_Reset": "Reset",
  "Image_Tools_Crop_Image": "Crop Image",
  "Image_Tools_Crop_Text": "Crop a portion out of the physical image. This can be undone any time. The original image will remain stored.",
  "Image_Tools_Crop_KeepRatio": "Keep ratio",
  "Image_Tools_Crop_None": "None",
  "Image_Tools_Crop_Set_Ratio": "Set ratio",
  "Image_Tools_Crop_Size": "Crop Size",
  "Image_Tools_Crop_Position": "Position and Dimensions",
  "Image_Tools_Image_Brightness": "Brightness",
  "Image_Tools_Image_Colors": "Image Colors",
  "Image_Tools_Image_Contrast": "Contrast",
  "Image_Tools_Image_Hue": "Hue",
  "Image_Tools_Image_Saturation": "Saturation",
  "Image_Tools_Transparent_Colors": "Transparent Color",
  "Image_Tools_Picker_Text" : "Select an image to create a figure at the current position. Click on an image to see it in full resolution.",
  "InternalLink_Tool_Caption": "Caption",
  "InternalLink_Tool_Search": "Search",
  "InternalLink_Tool_Internal_Links": "Internal Links",
  "InternalLink_Tool_Text": "Add an element that hyperlinks to a place inside this text.",
  "Listing_Listing": "Listing",
  "Properties_AllowChapters_Label": "User can append chapters",
  "Properties_AllowMetadata_Label": "User can use Meta Data for elements",
  "Properties_Defaults": "Defaults",
  "Properties_Defaults_ChapterTitle": "Chapter Title",
  "Properties_Defaults_Listing": "Listing",
  "Properties_Defaults_SectionTitle": "Section Title",
  "Properties_Defaults_Text": "Text",
  "Properties_Document_Properties": "Document Properties",
  "Properties_Legend": "Permit Functions",
  "Properties_ShowFunctions": "Show Functions",
  "Properties_ShowFunctions_FlowPane": "Bar with element symbols (left)",
  "Properties_ShowFunctions_NaviPane": "Bar with navigation elements (right)",
  "Properties_Text": "Shows properties that apply to this document while editing.",
  "Propertires_Behavior_Legend": "Behavior of presentation",
  "Propertires_Behavior_ShowNumberChain": "Section appear with 1., 1.1., 1.1.1 (otherwise #1, #2, #3 and so on)",
  "Semantic_Empty": "List is empty",
  "Table_Table": "Table",
  "Comments_Document_Text": "Comments provide a way to interact with your peers and readers.<br/>Meta data help readers to find relevant content.",
  "Comments_Document_Me": "Private Comments",
  "Comments_Document_Team": "Team Members' Comments",
  "Comments_Document_Reader": "Readers' Comments",
  "Comments_Tools_Btn_Add": "Add Comment",
  "Comments_Tools_Btn_Cancel": "Close",
  "Comments_Me_Comments_Add": "Add a new comment here. Subject: ",
  "Comments_Me_Comments_Existing": "See your private comments:",
  "Comments_Team_Comments_Add": "Write your contributors here. Subject: ",
  "Comments_Team_Comments_Existing": "See you peers comments:",
  "Comments_Reader_Comments_Add": "Answer your readers here. Subject: ",
  "Comments_Reader_Comments_Existing": "See you readers comments:",
  "Comments_MetaData": "Meta Data",
  "Comments_MetaData_Hint":"Meta Data for Snippets support the search matrix algorithm.",
  "Comments_MetaData_Btn_Save": "Save Data",
  "Comments_Reader_Close_Thread": "Close Thread",
  "Upload_Title_Text": "Upload images to the local documents repository and optionally add one to the document immediately.",
  "Upload_Title": "Image Upload",
  "Upload_Legend_Upload": "Select Files...",
  "Upload_Button_Add": "Add File",
  "Upload_Error_Common": "A common error occured uploading the file. Please repeat.",
  "Upload_Error_MaxFileSize": "The maximum size of a file exceeded (50 MB).",
  "Upload_Error_MinFileSize": "File is smaller than the minimum size of a file (100 Bytes).",
  "Upload_Error_FileTypes": "This type of file is not allowed.",
  "Upload_Error_MaxNumber": "The maximum number of files has been reached.",
  "Upload_Error_EmptyResult": "There was nothing uploaded. Please try again.",
  "Upload_Error_Bytes": "There was an error reading the bytes.",
  "Upload_Error_1": "File exceeds upload_max_filesize.",
  "Upload_Error_2": "File exceeds MAX_FILE_SIZE.",
  "Upload_Error_3": "File was only partially uploaded.",
  "Upload_Error_4": "No File was uploaded.",
  "Upload_Error_5": "Missing a temporary folder.",
  "Upload_Error_6": "Failed to write file to disk.",
  "Upload_Error_7": "File upload stopped by extension.",
  "Upload_Button_Ok": "OK",
  "Upload_Button_Cancel": "Cancel & Close",
  "Reorganize_Tools_Btn_Cancel": "Close",
  "Reorganize_Tools_Btn_Undo": "Undo & Close",
  "Reorganize_Text": "Reorganize the hierarchy of content within the text. Drag and Drop elements. Changes apply immediately."
};