//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texxtoor.DataModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControllerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControllerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Texxtoor.DataModels.ModelResources.ControllerResources", typeof(ControllerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string AccountController_ChangePassword_The_current_password_is_incorrect_or_the_new_password_is_invalid_ {
            get {
                return ResourceManager.GetString("AccountController_ChangePassword_The_current_password_is_incorrect_or_the_new_pas" +
                        "sword_is_invalid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized..
        /// </summary>
        public static string AccountController_ConfirmAssociation_You_are_not_authorized {
            get {
                return ResourceManager.GetString("AccountController_ConfirmAssociation_You_are_not_authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File moved to recycle bin..
        /// </summary>
        public static string AccountController_DeleteUserFile_File_moved_to_recycle_bin_ {
            get {
                return ResourceManager.GetString("AccountController_DeleteUserFile_File_moved_to_recycle_bin_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File removed from recycle bin..
        /// </summary>
        public static string AccountController_DeleteUserFilePermanently_File_removed_from_recycle_bin_ {
            get {
                return ResourceManager.GetString("AccountController_DeleteUserFilePermanently_File_removed_from_recycle_bin_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese E-Mail ist nicht bekannt..
        /// </summary>
        public static string AccountController_ExternalLoginAssociation_This_email_is_not_registered_with_us {
            get {
                return ResourceManager.GetString("AccountController_ExternalLoginAssociation_This_email_is_not_registered_with_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect.
        /// </summary>
        public static string AccountController_LogOn_The_user_name_or_password_provided_is_incorrect {
            get {
                return ResourceManager.GetString("AccountController_LogOn_The_user_name_or_password_provided_is_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix value added to list.
        /// </summary>
        public static string AccountController_Matrix_Added {
            get {
                return ResourceManager.GetString("AccountController_Matrix_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix value changed.
        /// </summary>
        public static string AccountController_Matrix_Changed {
            get {
                return ResourceManager.GetString("AccountController_Matrix_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix value removed from list.
        /// </summary>
        public static string AccountController_Matrix_Removed {
            get {
                return ResourceManager.GetString("AccountController_Matrix_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error filling form..
        /// </summary>
        public static string AccountController_QuickForm_Fehler_beim_Ausfüllen_der_Form_ {
            get {
                return ResourceManager.GetString("AccountController_QuickForm_Fehler_beim_Ausfüllen_der_Form_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is active now..
        /// </summary>
        public static string AccountController_RecoverUserFile_File_is_active_now_ {
            get {
                return ResourceManager.GetString("AccountController_RecoverUserFile_File_is_active_now_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt bereits ein Konto mit dieser E-Mail-Adresse..
        /// </summary>
        public static string AccountController_Register_An_account_with_this_email_already_exists_ {
            get {
                return ResourceManager.GetString("AccountController_Register_An_account_with_this_email_already_exists_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name provided has not been found as both, username or email. Call us at 0700-texxtoor for assistence..
        /// </summary>
        public static string AccountController_ResendActivationMail_The_name_provided_has_not_been_found {
            get {
                return ResourceManager.GetString("AccountController_ResendActivationMail_The_name_provided_has_not_been_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string AccountController_RetrievePassword_The_current_password_is_incorrect_or_the_new_password_is_invalid_ {
            get {
                return ResourceManager.GetString("AccountController_RetrievePassword_The_current_password_is_incorrect_or_the_new_p" +
                        "assword_is_invalid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile saved.
        /// </summary>
        public static string AccountController_Userprofile_Saved {
            get {
                return ResourceManager.GetString("AccountController_Userprofile_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving profile. Please try again..
        /// </summary>
        public static string AccountController_Userprofile_SavedError {
            get {
                return ResourceManager.GetString("AccountController_Userprofile_SavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your share amount for {0}.
        /// </summary>
        public static string AccountingManager_HandleRevenueShare_Your_share_amount_for__0_ {
            get {
                return ResourceManager.GetString("AccountingManager_HandleRevenueShare_Your_share_amount_for__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string AccountValidation_ErrorCodeToString_A_username_for_that_e_mail_address_already_exists {
            get {
                return ResourceManager.GetString("AccountValidation_ErrorCodeToString_A_username_for_that_e_mail_address_already_ex" +
                        "ists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string AccountValidation_ErrorCodeToString_An_unknown_error_occurred {
            get {
                return ResourceManager.GetString("AccountValidation_ErrorCodeToString_An_unknown_error_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string AccountValidation_ErrorCodeToString_The_authentication_provider_returned_an_error {
            get {
                return ResourceManager.GetString("AccountValidation_ErrorCodeToString_The_authentication_provider_returned_an_error" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string AccountValidation_ErrorCodeToString_The_e_mail_address_provided_is_invalid {
            get {
                return ResourceManager.GetString("AccountValidation_ErrorCodeToString_The_e_mail_address_provided_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string AccountValidation_ErrorCodeToString_The_password_provided_is_invalid {
            get {
                return ResourceManager.GetString("AccountValidation_ErrorCodeToString_The_password_provided_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string AccountValidation_ErrorCodeToString_The_password_retrieval_answer_provided_is_invalid {
            get {
                return ResourceManager.GetString("AccountValidation_ErrorCodeToString_The_password_retrieval_answer_provided_is_inv" +
                        "alid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string AccountValidation_ErrorCodeToString_The_password_retrieval_question_provided_is_invalid {
            get {
                return ResourceManager.GetString("AccountValidation_ErrorCodeToString_The_password_retrieval_question_provided_is_i" +
                        "nvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string AccountValidation_ErrorCodeToString_The_user_creation_request_has_been_canceled {
            get {
                return ResourceManager.GetString("AccountValidation_ErrorCodeToString_The_user_creation_request_has_been_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string AccountValidation_ErrorCodeToString_The_user_name_provided_is_invalid {
            get {
                return ResourceManager.GetString("AccountValidation_ErrorCodeToString_The_user_name_provided_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists. Please enter a different user name..
        /// </summary>
        public static string AccountValidation_ErrorCodeToString_Username_already_exists {
            get {
                return ResourceManager.GetString("AccountValidation_ErrorCodeToString_Username_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string CommunityController_SaveProfile_Fehler_ {
            get {
                return ResourceManager.GetString("CommunityController_SaveProfile_Fehler_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile saved.
        /// </summary>
        public static string CommunityController_SaveProfile_Profil_gespeichert {
            get {
                return ResourceManager.GetString("CommunityController_SaveProfile_Profil_gespeichert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment saved.
        /// </summary>
        public static string EditorController_Editor_CommentSaved {
            get {
                return ResourceManager.GetString("EditorController_Editor_CommentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties saved.
        /// </summary>
        public static string EditorController_Editor_PropertiesSaved {
            get {
                return ResourceManager.GetString("EditorController_Editor_PropertiesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer added.
        /// </summary>
        public static string GroupsController_AddAnswer_Answer_added {
            get {
                return ResourceManager.GetString("GroupsController_AddAnswer_Answer_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group created.
        /// </summary>
        public static string GroupsController_AddGroup_Group_created {
            get {
                return ResourceManager.GetString("GroupsController_AddGroup_Group_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question created.
        /// </summary>
        public static string GroupsController_AddQuestion_Question_created {
            get {
                return ResourceManager.GetString("GroupsController_AddQuestion_Question_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group deleted.
        /// </summary>
        public static string GroupsController_DeleteGroup_Group_deleted {
            get {
                return ResourceManager.GetString("GroupsController_DeleteGroup_Group_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group changed.
        /// </summary>
        public static string GroupsController_EditGroup_Group_changed {
            get {
                return ResourceManager.GetString("GroupsController_EditGroup_Group_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question changed.
        /// </summary>
        public static string GroupsController_EditQuestion_Question_changed {
            get {
                return ResourceManager.GetString("GroupsController_EditQuestion_Question_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The favorite item is already in the list.
        /// </summary>
        public static string HomeController_AddFavorite_Already_There {
            get {
                return ResourceManager.GetString("HomeController_AddFavorite_Already_There", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite added.
        /// </summary>
        public static string HomeController_AddFavorite_Favorite_added {
            get {
                return ResourceManager.GetString("HomeController_AddFavorite_Favorite_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickstart project {0} created at {1}.
        /// </summary>
        public static string HomeController_QuickFormAuthor_Quickstart_project__0__created_at__1_ {
            get {
                return ResourceManager.GetString("HomeController_QuickFormAuthor_Quickstart_project__0__created_at__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team for project {0} (Quick Start).
        /// </summary>
        public static string HomeController_QuickFormAuthor_Team_for_project__0___Quick_Start_ {
            get {
                return ResourceManager.GetString("HomeController_QuickFormAuthor_Team_for_project__0___Quick_Start_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project {0}, created at {1} was build by using the quick start function. Consider changing this text to help your fellow team members understanding the goal..
        /// </summary>
        public static string HomeController_QuickFormAuthor_The_project__0___created_at__1__was_build {
            get {
                return ResourceManager.GetString("HomeController_QuickFormAuthor_The_project__0___created_at__1__was_build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite entry removed.
        /// </summary>
        public static string HomeController_RemoveFavorite_Favorite_entry_removed {
            get {
                return ResourceManager.GetString("HomeController_RemoveFavorite_Favorite_entry_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing package added.
        /// </summary>
        public static string MarketingController_Add_MarketingPackage {
            get {
                return ResourceManager.GetString("MarketingController_Add_MarketingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete package.
        /// </summary>
        public static string MarketingController_Delete_MarketingPackage_Cannot {
            get {
                return ResourceManager.GetString("MarketingController_Delete_MarketingPackage_Cannot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete Package because it is in use..
        /// </summary>
        public static string MarketingController_Delete_MarketingPackage_InUse {
            get {
                return ResourceManager.GetString("MarketingController_Delete_MarketingPackage_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package deleted.
        /// </summary>
        public static string MarketingController_Delete_MarketingPackage_Success {
            get {
                return ResourceManager.GetString("MarketingController_Delete_MarketingPackage_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing package changed.
        /// </summary>
        public static string MarketingController_Edit_MarketingPackage {
            get {
                return ResourceManager.GetString("MarketingController_Edit_MarketingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Saved.
        /// </summary>
        public static string MarketingController_Saved_BasePrice {
            get {
                return ResourceManager.GetString("MarketingController_Saved_BasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save, the price is invalid.
        /// </summary>
        public static string MarketingController_Saved_BasePrice_Error {
            get {
                return ResourceManager.GetString("MarketingController_Saved_BasePrice_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares Saved.
        /// </summary>
        public static string MarketingController_Saved_Shares {
            get {
                return ResourceManager.GetString("MarketingController_Saved_Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save, shares sum exceeds 100%.
        /// </summary>
        public static string MarketingController_Saved_Shares_Error {
            get {
                return ResourceManager.GetString("MarketingController_Saved_Shares_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned package &apos;{0}&apos; to project &apos;{1}&apos;.
        /// </summary>
        public static string MarketingController_Set_MarketingPackage {
            get {
                return ResourceManager.GetString("MarketingController_Set_MarketingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Profile.
        /// </summary>
        public static string MenuService_CreatePropertyBag_No_Profile {
            get {
                return ResourceManager.GetString("MenuService_CreatePropertyBag_No_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Exists.
        /// </summary>
        public static string MenuService_CreatePropertyBag_Profile_Exists {
            get {
                return ResourceManager.GetString("MenuService_CreatePropertyBag_Profile_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully send !.
        /// </summary>
        public static string MessagingController_AddMessage_Successfully_send__ {
            get {
                return ResourceManager.GetString("MessagingController_AddMessage_Successfully_send__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message deleted..
        /// </summary>
        public static string MessagingController_DeleteMessage_Message_deleted__ {
            get {
                return ResourceManager.GetString("MessagingController_DeleteMessage_Message_deleted__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must at least select one user.
        /// </summary>
        public static string MessagingController_SendMessage_You_must_at_least_select_one_user {
            get {
                return ResourceManager.GetString("MessagingController_SendMessage_You_must_at_least_select_one_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience added.
        /// </summary>
        public static string OpusController_Audience_Added {
            get {
                return ResourceManager.GetString("OpusController_Audience_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience changed.
        /// </summary>
        public static string OpusController_Audience_Changed {
            get {
                return ResourceManager.GetString("OpusController_Audience_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience removed.
        /// </summary>
        public static string OpusController_Audience_Removed {
            get {
                return ResourceManager.GetString("OpusController_Audience_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Team.
        /// </summary>
        public static string OpusController_CreateFromTemplateSimple__0_s_Team {
            get {
                return ResourceManager.GetString("OpusController_CreateFromTemplateSimple__0_s_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Team for a simple project.
        /// </summary>
        public static string OpusController_CreateFromTemplateSimple__0_s_Team_for_a_simple_project {
            get {
                return ResourceManager.GetString("OpusController_CreateFromTemplateSimple__0_s_Team_for_a_simple_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple project created implicitly.
        /// </summary>
        public static string OpusController_CreateFromTemplateSimple_A_simple_project_created_implicitly {
            get {
                return ResourceManager.GetString("OpusController_CreateFromTemplateSimple_A_simple_project_created_implicitly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Text.
        /// </summary>
        public static string OpusController_CreateFromTemplateSimple_New_Book {
            get {
                return ResourceManager.GetString("OpusController_CreateFromTemplateSimple_New_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Project.
        /// </summary>
        public static string OpusController_CreateFromTemplateSimple_Simple_Project {
            get {
                return ResourceManager.GetString("OpusController_CreateFromTemplateSimple_Simple_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History deleted.
        /// </summary>
        public static string OpusController_Document_HistoryDeleted {
            get {
                return ResourceManager.GetString("OpusController_Document_HistoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document restored.
        /// </summary>
        public static string OpusController_Document_Restored {
            get {
                return ResourceManager.GetString("OpusController_Document_Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured sending data. Please check the form..
        /// </summary>
        public static string OpusController_Edit_An_error_occured_sending_data__Please_check_the_form_ {
            get {
                return ResourceManager.GetString("OpusController_Edit_An_error_occured_sending_data__Please_check_the_form_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text information saved.
        /// </summary>
        public static string OpusController_Edit_Text_information_saved {
            get {
                return ResourceManager.GetString("OpusController_Edit_Text_information_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters merged to target text.
        /// </summary>
        public static string OpusController_Merge_Text_Ok {
            get {
                return ResourceManager.GetString("OpusController_Merge_Text_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone added.
        /// </summary>
        public static string OpusController_Milestone_Added {
            get {
                return ResourceManager.GetString("OpusController_Milestone_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add because the provided name is empty or invalid.
        /// </summary>
        public static string OpusController_Milestone_CannotAdd_NameInvalid {
            get {
                return ResourceManager.GetString("OpusController_Milestone_CannotAdd_NameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone changed.
        /// </summary>
        public static string OpusController_Milestone_Changed {
            get {
                return ResourceManager.GetString("OpusController_Milestone_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone removed.
        /// </summary>
        public static string OpusController_Milestone_Deleted {
            get {
                return ResourceManager.GetString("OpusController_Milestone_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove milestone.
        /// </summary>
        public static string OpusController_Milestone_DeleteError {
            get {
                return ResourceManager.GetString("OpusController_Milestone_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miletstone renamed.
        /// </summary>
        public static string OpusController_Milestone_Edited {
            get {
                return ResourceManager.GetString("OpusController_Milestone_Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename because the name is empty or invalid.
        /// </summary>
        public static string OpusController_Milestone_Edited_InvalidName {
            get {
                return ResourceManager.GetString("OpusController_Milestone_Edited_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone moved.
        /// </summary>
        public static string OpusController_Milestone_Moved {
            get {
                return ResourceManager.GetString("OpusController_Milestone_Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review added.
        /// </summary>
        public static string OpusController_Review_Added {
            get {
                return ResourceManager.GetString("OpusController_Review_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review changed.
        /// </summary>
        public static string OpusController_Review_Changed {
            get {
                return ResourceManager.GetString("OpusController_Review_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review removed.
        /// </summary>
        public static string OpusController_Review_Deleted {
            get {
                return ResourceManager.GetString("OpusController_Review_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order for {0}.
        /// </summary>
        public static string OrderManager_CreateOrderProductInternal_Order_for__0_ {
            get {
                return ResourceManager.GetString("OrderManager_CreateOrderProductInternal_Order_for__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &apos;{0}&apos; has been removed..
        /// </summary>
        public static string OrdersController_DeletePreOrder_Product___0___has_been_removed_ {
            get {
                return ResourceManager.GetString("OrdersController_DeletePreOrder_Product___0___has_been_removed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product cannot be removed..
        /// </summary>
        public static string OrdersController_DeletePreOrder_Product_cannot_be_removed_ {
            get {
                return ResourceManager.GetString("OrdersController_DeletePreOrder_Product_cannot_be_removed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address changed..
        /// </summary>
        public static string OrdersController_OrderAddress_Address_changed_ {
            get {
                return ResourceManager.GetString("OrdersController_OrderAddress_Address_changed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user profile, purchase cannot be stored permanently..
        /// </summary>
        public static string OrdersController_OrderAddress_No_user_profile__purchase_cannot_be_stored_permanently_ {
            get {
                return ResourceManager.GetString("OrdersController_OrderAddress_No_user_profile__purchase_cannot_be_stored_permanen" +
                        "tly_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been set to types &apos;{0}&apos;..
        /// </summary>
        public static string OrdersController_OrderMedia_Product_has_been_set_to_types___0___ {
            get {
                return ResourceManager.GetString("OrdersController_OrderMedia_Product_has_been_set_to_types___0___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no media selected. Select at least one..
        /// </summary>
        public static string OrdersController_QuickMedia_There_are_no_media_selected__Select_at_least_one_ {
            get {
                return ResourceManager.GetString("OrdersController_QuickMedia_There_are_no_media_selected__Select_at_least_one_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw amount is not valid..
        /// </summary>
        public static string PaymentController_WithdrawAmount_AmountInvalid {
            get {
                return ResourceManager.GetString("PaymentController_WithdrawAmount_AmountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while processing the request..
        /// </summary>
        public static string PaymentController_WithdrawAmount_ErrorOccured {
            get {
                return ResourceManager.GetString("PaymentController_WithdrawAmount_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t add a PayPal account Id in your profile. You can add from payment section..
        /// </summary>
        public static string PaymentController_WithdrawAmount_NoAccount {
            get {
                return ResourceManager.GetString("PaymentController_WithdrawAmount_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount has been successfully transferred to your paypal account..
        /// </summary>
        public static string PaymentController_WithdrawAmount_SuccessTransfer {
            get {
                return ResourceManager.GetString("PaymentController_WithdrawAmount_SuccessTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating the file..
        /// </summary>
        public static string ProductionController_ProduceMedia_An_error_occured_while_creating_the_file {
            get {
                return ResourceManager.GetString("ProductionController_ProduceMedia_An_error_occured_while_creating_the_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} has been created. You can download the file from your local archive..
        /// </summary>
        public static string ProductionController_ProduceMedia_The_file__0__has_been_created {
            get {
                return ResourceManager.GetString("ProductionController_ProduceMedia_The_file__0__has_been_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s Preview.
        /// </summary>
        public static string ProductionManager_CreatePdf_Author_s_Preview {
            get {
                return ResourceManager.GetString("ProductionManager_CreatePdf_Author_s_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a preview that shows the final appearance of the printed book.
        /// </summary>
        public static string ProductionManager_CreatePdf_This_is_a_preview_that_shows_the_final_appearance_of_the_printed_book {
            get {
                return ResourceManager.GetString("ProductionManager_CreatePdf_This_is_a_preview_that_shows_the_final_appearance_of_" +
                        "the_printed_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string ProductionManager_Div_Figure {
            get {
                return ResourceManager.GetString("ProductionManager_Div_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string ProductionManager_Div_Listing {
            get {
                return ResourceManager.GetString("ProductionManager_Div_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductionManager_Div_Sec1 {
            get {
                return ResourceManager.GetString("ProductionManager_Div_Sec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductionManager_Div_Sec2 {
            get {
                return ResourceManager.GetString("ProductionManager_Div_Sec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductionManager_Div_Sec3 {
            get {
                return ResourceManager.GetString("ProductionManager_Div_Sec3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductionManager_Div_Sec4 {
            get {
                return ResourceManager.GetString("ProductionManager_Div_Sec4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductionManager_Div_Sec5 {
            get {
                return ResourceManager.GetString("ProductionManager_Div_Sec5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductionManager_Div_Sec6 {
            get {
                return ResourceManager.GetString("ProductionManager_Div_Sec6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string ProductionManager_Div_Table {
            get {
                return ResourceManager.GetString("ProductionManager_Div_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure.
        /// </summary>
        public static string ProductionManager_Label_Figure {
            get {
                return ResourceManager.GetString("ProductionManager_Label_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        public static string ProductionManager_Label_Listing {
            get {
                return ResourceManager.GetString("ProductionManager_Label_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#160;&amp;#160;.
        /// </summary>
        public static string ProductionManager_Label_Sec1 {
            get {
                return ResourceManager.GetString("ProductionManager_Label_Sec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#160;&amp;#160;.
        /// </summary>
        public static string ProductionManager_Label_Sec2 {
            get {
                return ResourceManager.GetString("ProductionManager_Label_Sec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#160;&amp;#160;.
        /// </summary>
        public static string ProductionManager_Label_Sec3 {
            get {
                return ResourceManager.GetString("ProductionManager_Label_Sec3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#160;&amp;#160;.
        /// </summary>
        public static string ProductionManager_Label_Sec4 {
            get {
                return ResourceManager.GetString("ProductionManager_Label_Sec4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#160;&amp;#160;.
        /// </summary>
        public static string ProductionManager_Label_Sec5 {
            get {
                return ResourceManager.GetString("ProductionManager_Label_Sec5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#160;&amp;#160;.
        /// </summary>
        public static string ProductionManager_Label_Sec6 {
            get {
                return ResourceManager.GetString("ProductionManager_Label_Sec6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string ProductionManager_Label_Table {
            get {
                return ResourceManager.GetString("ProductionManager_Label_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ProductionManager_Sep_Figure {
            get {
                return ResourceManager.GetString("ProductionManager_Sep_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ProductionManager_Sep_Listing {
            get {
                return ResourceManager.GetString("ProductionManager_Sep_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProductionManager_Sep_Sec1 {
            get {
                return ResourceManager.GetString("ProductionManager_Sep_Sec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string ProductionManager_Sep_Sec2 {
            get {
                return ResourceManager.GetString("ProductionManager_Sep_Sec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string ProductionManager_Sep_Sec3 {
            get {
                return ResourceManager.GetString("ProductionManager_Sep_Sec3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string ProductionManager_Sep_Sec4 {
            get {
                return ResourceManager.GetString("ProductionManager_Sep_Sec4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string ProductionManager_Sep_Sec5 {
            get {
                return ResourceManager.GetString("ProductionManager_Sep_Sec5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string ProductionManager_Sep_Sec6 {
            get {
                return ResourceManager.GetString("ProductionManager_Sep_Sec6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ProductionManager_Sep_Table {
            get {
                return ResourceManager.GetString("ProductionManager_Sep_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Create new Team *.
        /// </summary>
        public static string ProjectController_AddProject___Create_new_Team__ {
            get {
                return ResourceManager.GetString("ProjectController_AddProject___Create_new_Team__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Project created..
        /// </summary>
        public static string ProjectController_AddProject__0__Project_successfully_created_ {
            get {
                return ResourceManager.GetString("ProjectController_AddProject__0__Project_successfully_created_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;Internal Error: {0}.
        /// </summary>
        public static string ProjectController_ImportSimple__br_Internal_Error {
            get {
                return ResourceManager.GetString("ProjectController_ImportSimple__br_Internal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process this file properly..
        /// </summary>
        public static string ProjectController_ImportSimple_Could_not_process_this_file_properly {
            get {
                return ResourceManager.GetString("ProjectController_ImportSimple_Could_not_process_this_file_properly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data read but invalid zip file..
        /// </summary>
        public static string ProjectController_ImportSimple_Data_read_but_invalid_zip_file {
            get {
                return ResourceManager.GetString("ProjectController_ImportSimple_Data_read_but_invalid_zip_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOC/DOCX is currently not supported..
        /// </summary>
        public static string ProjectController_ImportSimple_DOC_DOCX_is_currently_not_supported {
            get {
                return ResourceManager.GetString("ProjectController_ImportSimple_DOC_DOCX_is_currently_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP file extracted but couldn&apos;t parse..
        /// </summary>
        public static string ProjectController_ImportSimple_ZIP_file_extracted_but_couldn_t_parse {
            get {
                return ResourceManager.GetString("ProjectController_ImportSimple_ZIP_file_extracted_but_couldn_t_parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP file has been processed. Return to Dashboard to view results..
        /// </summary>
        public static string ProjectController_ImportSimple_ZIP_file_has_been_processed__Return_to_Dashboard_to_view_results {
            get {
                return ResourceManager.GetString("ProjectController_ImportSimple_ZIP_file_has_been_processed__Return_to_Dashboard_t" +
                        "o_view_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP loaded but entries invalid..
        /// </summary>
        public static string ProjectController_ImportSimple_ZIP_loaded_but_entries_invalid {
            get {
                return ResourceManager.GetString("ProjectController_ImportSimple_ZIP_loaded_but_entries_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message created and send.
        /// </summary>
        public static string ProjectController_Message_Created {
            get {
                return ResourceManager.GetString("ProjectController_Message_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP file extracted but content not convertable..
        /// </summary>
        public static string ProjectController_ProcessSingleHtml_ZIP_file_extracted_but_content_not_convertable {
            get {
                return ResourceManager.GetString("ProjectController_ProcessSingleHtml_ZIP_file_extracted_but_content_not_convertabl" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP processed and content written to project..
        /// </summary>
        public static string ProjectController_ProcessSingleHtml_ZIP_processed_and_content_written_to_project {
            get {
                return ResourceManager.GetString("ProjectController_ProcessSingleHtml_ZIP_processed_and_content_written_to_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project activated.
        /// </summary>
        public static string ProjectController_Project_Activated {
            get {
                return ResourceManager.GetString("ProjectController_Project_Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project deactivated.
        /// </summary>
        public static string ProjectController_Project_Deactivated {
            get {
                return ResourceManager.GetString("ProjectController_Project_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project cannot be activated due to insufficient rights.
        /// </summary>
        public static string ProjectController_Project_NotActivated {
            get {
                return ResourceManager.GetString("ProjectController_Project_NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not deactivated due to current project state.
        /// </summary>
        public static string ProjectController_Project_NotDeactivated {
            get {
                return ResourceManager.GetString("ProjectController_Project_NotDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkItem Comment.
        /// </summary>
        public static string ProjectManager_AddCommentForWorkitem_WorkItem_Comment {
            get {
                return ResourceManager.GetString("ProjectManager_AddCommentForWorkitem_WorkItem_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkItem Comment.
        /// </summary>
        public static string ProjectManager_AddCommentForWorkitem_WorkItem_Name {
            get {
                return ResourceManager.GetString("ProjectManager_AddCommentForWorkitem_WorkItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Editing.
        /// </summary>
        public static string ProjectManager_CreateDefaultMileStones_Copy_Editing {
            get {
                return ResourceManager.GetString("ProjectManager_CreateDefaultMileStones_Copy_Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyEditing.
        /// </summary>
        public static string ProjectManager_CreateDefaultMileStones_CopyEditing {
            get {
                return ResourceManager.GetString("ProjectManager_CreateDefaultMileStones_CopyEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Content.
        /// </summary>
        public static string ProjectManager_CreateDefaultMileStones_Create_Content {
            get {
                return ResourceManager.GetString("ProjectManager_CreateDefaultMileStones_Create_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Illustrations.
        /// </summary>
        public static string ProjectManager_CreateDefaultMileStones_Create_Illustrations {
            get {
                return ResourceManager.GetString("ProjectManager_CreateDefaultMileStones_Create_Illustrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Marketing Package.
        /// </summary>
        public static string ProjectManager_CreateDefaultMileStones_Create_Marketing_Package {
            get {
                return ResourceManager.GetString("ProjectManager_CreateDefaultMileStones_Create_Marketing_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrations.
        /// </summary>
        public static string ProjectManager_CreateDefaultMileStones_Illustrations {
            get {
                return ResourceManager.GetString("ProjectManager_CreateDefaultMileStones_Illustrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string ProjectManager_CreateDefaultMileStones_Marketing {
            get {
                return ResourceManager.GetString("ProjectManager_CreateDefaultMileStones_Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof.
        /// </summary>
        public static string ProjectManager_CreateDefaultMileStones_Proof {
            get {
                return ResourceManager.GetString("ProjectManager_CreateDefaultMileStones_Proof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof Read.
        /// </summary>
        public static string ProjectManager_CreateDefaultMileStones_Proof_Read {
            get {
                return ResourceManager.GetString("ProjectManager_CreateDefaultMileStones_Proof_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string ProjectManager_CreateDefaultMileStones_Writing {
            get {
                return ResourceManager.GetString("ProjectManager_CreateDefaultMileStones_Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter .
        /// </summary>
        public static string ProjectManager_CreateFromTemplate_Chapter_ {
            get {
                return ResourceManager.GetString("ProjectManager_CreateFromTemplate_Chapter_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Chapter.
        /// </summary>
        public static string ProjectManager_CreateFromTemplate_First_Chapter {
            get {
                return ResourceManager.GetString("ProjectManager_CreateFromTemplate_First_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string ProjectManager_CreateFromTemplate_Index {
            get {
                return ResourceManager.GetString("ProjectManager_CreateFromTemplate_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preface.
        /// </summary>
        public static string ProjectManager_CreateFromTemplate_Preface {
            get {
                return ResourceManager.GetString("ProjectManager_CreateFromTemplate_Preface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Team.
        /// </summary>
        public static string ProjectManager_CreateProject__0__Team {
            get {
                return ResourceManager.GetString("ProjectManager_CreateProject__0__Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string ProjectManager_CreateProject__Package {
            get {
                return ResourceManager.GetString("ProjectManager_CreateProject__Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        public static string ProjectManager_CreateProject_Chapter {
            get {
                return ResourceManager.GetString("ProjectManager_CreateProject_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Marketing Package for project {0}.
        /// </summary>
        public static string ProjectManager_CreateProject_Primary_Marketing_Package_for_project_ {
            get {
                return ResourceManager.GetString("ProjectManager_CreateProject_Primary_Marketing_Package_for_project_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete, team runs active projects.
        /// </summary>
        public static string ProjectManager_DeleteTeam_Cannot_delete__team_runs_active_projects {
            get {
                return ResourceManager.GetString("ProjectManager_DeleteTeam_Cannot_delete__team_runs_active_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the team leader can delete a team.
        /// </summary>
        public static string ProjectManager_DeleteTeam_Only_the_team_leader_can_delete_a_team {
            get {
                return ResourceManager.GetString("ProjectManager_DeleteTeam_Only_the_team_leader_can_delete_a_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team deleted.
        /// </summary>
        public static string ProjectManager_DeleteTeam_Team_deleted {
            get {
                return ResourceManager.GetString("ProjectManager_DeleteTeam_Team_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team not found.
        /// </summary>
        public static string ProjectManager_DeleteTeam_Team_not_found {
            get {
                return ResourceManager.GetString("ProjectManager_DeleteTeam_Team_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article {0} has been published by {1} at {2}.
        /// </summary>
        public static string ProjectManager_GetOrCreatePublished_Article_Title {
            get {
                return ResourceManager.GetString("ProjectManager_GetOrCreatePublished_Article_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Package.
        /// </summary>
        public static string ProjectManager_GetPublishedAndLoad_Default_Package {
            get {
                return ResourceManager.GetString("ProjectManager_GetPublishedAndLoad_Default_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Package.
        /// </summary>
        public static string ProjectManager_GetPublishedAndLoad_Generated_Package {
            get {
                return ResourceManager.GetString("ProjectManager_GetPublishedAndLoad_Generated_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Termset.
        /// </summary>
        public static string ProjectManager_GetTermSetsForProject_Default_Termset {
            get {
                return ResourceManager.GetString("ProjectManager_GetTermSetsForProject_Default_Termset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First public termset for the specific project..
        /// </summary>
        public static string ProjectManager_GetTermSetsForProject_First_public_termset_for_the_specific_project_ {
            get {
                return ResourceManager.GetString("ProjectManager_GetTermSetsForProject_First_public_termset_for_the_specific_projec" +
                        "t_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the default termset that keeps all terms not defined in specific termsets.
        /// </summary>
        public static string ProjectManager_GetTermSetsForProject_This_is_the_default_termset_that_keeps_all_terms_not_defined_in_specific_termsets {
            get {
                return ResourceManager.GetString("ProjectManager_GetTermSetsForProject_This_is_the_default_termset_that_keeps_all_t" +
                        "erms_not_defined_in_specific_termsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        public static string PublishingController_AuthorPreview_Not_Set {
            get {
                return ResourceManager.GetString("PublishingController_AuthorPreview_Not_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing EPUB.
        /// </summary>
        public static string PublishingController_Processing_EPUB {
            get {
                return ResourceManager.GetString("PublishingController_Processing_EPUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start processing EPUB. You&apos;ll be notified by email once the file is available in the archive..
        /// </summary>
        public static string PublishingController_Processing_EPUBText {
            get {
                return ResourceManager.GetString("PublishingController_Processing_EPUBText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing HTML.
        /// </summary>
        public static string PublishingController_Processing_HTML {
            get {
                return ResourceManager.GetString("PublishingController_Processing_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show HTML or download.
        /// </summary>
        public static string PublishingController_Processing_HTMLText {
            get {
                return ResourceManager.GetString("PublishingController_Processing_HTMLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing of PDF done.
        /// </summary>
        public static string PublishingController_Processing_PDF {
            get {
                return ResourceManager.GetString("PublishingController_Processing_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to download the PDF preview file..
        /// </summary>
        public static string PublishingController_Processing_PDFText {
            get {
                return ResourceManager.GetString("PublishingController_Processing_PDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing of RSS done.
        /// </summary>
        public static string PublishingController_Processing_RSS {
            get {
                return ResourceManager.GetString("PublishingController_Processing_RSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Image to upload custom cover..
        /// </summary>
        public static string PublishingController_SetCover_Click_Image_to_upload_custom {
            get {
                return ResourceManager.GetString("PublishingController_SetCover_Click_Image_to_upload_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} comment deleted.
        /// </summary>
        public static string ReaderController_DeleteComment__0__comment_deleted {
            get {
                return ResourceManager.GetString("ReaderController_DeleteComment__0__comment_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} comments deleted.
        /// </summary>
        public static string ReaderController_DeleteComments__0__comments_deleted {
            get {
                return ResourceManager.GetString("ReaderController_DeleteComments__0__comments_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work {0} is being deleted..
        /// </summary>
        public static string ReaderController_DeleteWork_Work_deleted {
            get {
                return ResourceManager.GetString("ReaderController_DeleteWork_Work_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work {0} changed.
        /// </summary>
        public static string ReaderController_EditWork_Work_changed {
            get {
                return ResourceManager.GetString("ReaderController_EditWork_Work_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from {0}.
        /// </summary>
        public static string ReaderManager_CopyWork_Copy_from {
            get {
                return ResourceManager.GetString("ReaderManager_CopyWork_Copy_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Collection.
        /// </summary>
        public static string ReaderManager_CreateAutoNameForUser_New_Collection {
            get {
                return ResourceManager.GetString("ReaderManager_CreateAutoNameForUser_New_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product .
        /// </summary>
        public static string ReaderManager_GatOrAddProductForWork_Product_ {
            get {
                return ResourceManager.GetString("ReaderManager_GatOrAddProductForWork_Product_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Collection.
        /// </summary>
        public static string ReaderManager_GetFragmentNavigation_Automatic_Collection {
            get {
                return ResourceManager.GetString("ReaderManager_GetFragmentNavigation_Automatic_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Text.
        /// </summary>
        public static string ReaderManager_GetFragmentTree_Empty_Book {
            get {
                return ResourceManager.GetString("ReaderManager_GetFragmentTree_Empty_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files deleted.
        /// </summary>
        public static string ResourceController_EmptyTrash_Files_deleted {
            get {
                return ResourceManager.GetString("ResourceController_EmptyTrash_Files_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files deleted. You can only delete your private files finally..
        /// </summary>
        public static string ResourceController_EmptyTrash_No_files_deleted {
            get {
                return ResourceManager.GetString("ResourceController_EmptyTrash_No_files_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term added.
        /// </summary>
        public static string ResourceController_Term_Added {
            get {
                return ResourceManager.GetString("ResourceController_Term_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term changed.
        /// </summary>
        public static string ResourceController_Term_Changed {
            get {
                return ResourceManager.GetString("ResourceController_Term_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term removed.
        /// </summary>
        public static string ResourceController_Term_Removed {
            get {
                return ResourceManager.GetString("ResourceController_Term_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termset added.
        /// </summary>
        public static string ResourceController_Termset_Added {
            get {
                return ResourceManager.GetString("ResourceController_Termset_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding termset ({0}).
        /// </summary>
        public static string ResourceController_Termset_AddedError {
            get {
                return ResourceManager.GetString("ResourceController_Termset_AddedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termset changed.
        /// </summary>
        public static string ResourceController_Termset_Changed {
            get {
                return ResourceManager.GetString("ResourceController_Termset_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error changing termset ({0}).
        /// </summary>
        public static string ResourceController_Termset_ChangedError {
            get {
                return ResourceManager.GetString("ResourceController_Termset_ChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termset removed.
        /// </summary>
        public static string ResourceController_Termset_Removed {
            get {
                return ResourceManager.GetString("ResourceController_Termset_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing termset ({0}).
        /// </summary>
        public static string ResourceController_Termset_RemovedError {
            get {
                return ResourceManager.GetString("ResourceController_Termset_RemovedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member added.
        /// </summary>
        public static string TeamController_AddMember_Member_added {
            get {
                return ResourceManager.GetString("TeamController_AddMember_Member_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team &apos;{0}&apos; created..
        /// </summary>
        public static string TeamController_AddTeam__0__Team_successfully_created_ {
            get {
                return ResourceManager.GetString("TeamController_AddTeam__0__Team_successfully_created_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role for team member assigned.
        /// </summary>
        public static string TeamController_AssignRole_Role_for_team_member_assigned {
            get {
                return ResourceManager.GetString("TeamController_AssignRole_Role_for_team_member_assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name changed to &apos;{0}&apos;..
        /// </summary>
        public static string TeamController_EditTeam_Team_name_changed_to {
            get {
                return ResourceManager.GetString("TeamController_EditTeam_Team_name_changed_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove member.
        /// </summary>
        public static string TeamController_RemoveMember_Cannot_remove_member {
            get {
                return ResourceManager.GetString("TeamController_RemoveMember_Cannot_remove_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member removed.
        /// </summary>
        public static string TeamController_RemoveMember_Member_removed {
            get {
                return ResourceManager.GetString("TeamController_RemoveMember_Member_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string UserManager_AddConsumerMatrixToProfile_New {
            get {
                return ResourceManager.GetString("UserManager_AddConsumerMatrixToProfile_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can write.
        /// </summary>
        public static string UserManager_AddContributorMatrixToProfile_I_can_write {
            get {
                return ResourceManager.GetString("UserManager_AddContributorMatrixToProfile_I_can_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has no wall profile.
        /// </summary>
        public static string UserManager_GetProfile_User_has_no_wall_profile {
            get {
                return ResourceManager.GetString("UserManager_GetProfile_User_has_no_wall_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        public static string UserManager_ValidateUser_Value_cannot_be_null_or_empty_ {
            get {
                return ResourceManager.GetString("UserManager_ValidateUser_Value_cannot_be_null_or_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be at least {1} characters long..
        /// </summary>
        public static string ValidatePasswordLengthAttribute_DefaultErrorMessage {
            get {
                return ResourceManager.GetString("ValidatePasswordLengthAttribute_DefaultErrorMessage", resourceCulture);
            }
        }
    }
}
