window.localize = window.localize || {};
window.localize.Panes = {
  "Document_Engine": "Engine",
  "Document_Engine_Bing": "Bing",
  "Document_Engine_Google": "Google",
  "Document_Options": "Options",
  "Document_AutoTrans": "Automatic Translation",
  "Format_Font_Bold": "Bold",
  "Format_Font_Italics": "Italics",
  "Format_Font_NonSemantic": "Font (non semantic)",
  "Format_Font_Sub": "Sub",
  "Format_Font_Sup": "Super",
  "Format_Font_Underline": "Underline",
  "Format_Formatting_Bullets": "Bullets",
  "Format_Formatting_Editing": "Editing",
  "Format_Formatting_Indent": "Indent",
  "Format_Formatting_NonSemantic": "Formatting (non semantic)",
  "Format_Formatting_Numbers": "Numbers",
  "Format_Formatting_Outdent": "Outdent",
  "Format_Formatting_Undo": "Undo",
  "Format_Formatting_RemoveFormat": "Remove Format",
  "Images_Delete": "Delete",
  "Images_DeleteImage": "Delete Image",
  "Images_Insert_Image": "Quick Insert Image",
  "Images_Insert": "Insert Image",
  "Images_Images": "Select Image",
  "Images_Upload": "Upload",
  "Images_Measures": "Measures",
  "Images_Measures_Height": "Height",
  "Images_Measures_Width": "Width",
  "Images_Tools": "Tools",
  "Images_Tools_Colors": "Colors",
  "Images_Tools_Crop": "Crop",
  "Image_Keep_Size": "Keep Size",
  "Navigate_Find": "Find",
  "Navigate_Replace": "Replace",
  "Navigate_Search": "Search",
  "Navigate_SelectAll": "Select All",
  "Semantic_Insert_Abbreviations": "Abbreviations",
  "Semantic_Insert_Cites": "Cites",
  "Semantic_Insert_Definitions": "Definitions",
  "Semantic_Insert_Elements": "Insert Elements (semantic)",
  "Semantic_Insert_Idiom": "Idiom",
  "Semantic_Insert_Index": "Index",
  "Semantic_Insert_Links": "Links",
  "Semantic_Insert_Variables": "Variables",
  "Semantic_Links": "Links",
  "Semantic_Links_AddInternal": "Add an internal link",
  "Semantic_Links_RemoveLink": "Remove link",
  "Semantic_MetaInformation": "Meta Information",
  "Semantic_MetaInformation_Stage": "Stage",
  "Semantic_MetaInformation_Target": "Target",
  "Semantic_Sidebar": "Sidebar",
  "Semantic_SocialInteraction": "Social Interaction",
  "Semantic_SocialInteraction_Comments": "Comments",
  "Semantic_Text_Elements": "Semantic Text",
  "Semantic_Text_Code": "Code",
  "Semantic_Text_File": "File",
  "Semantic_Text_Keyboard": "Keyboard",
  "Semantic_Type": "Type",
  "Write_Chapter": "Chapter",
  "Write_Clipboard": "Clipboard",
  "Write_Copy": "Copy",
  "Write_Cut": "Cut"
};