//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEXXTOOR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TEXXTOOR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.texxtoor.com.
        /// </summary>
        internal static string CommandService_GoToHome {
            get {
                return ResourceManager.GetString("CommandService_GoToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.texxtoor.com/AuthorPortal/Opus/Edit/.
        /// </summary>
        internal static string CommandService_GoToHome_Opus_Edit_ {
            get {
                return ResourceManager.GetString("CommandService_GoToHome_Opus_Edit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        internal static string CommandService_InsertLocalPicture_Open_Image {
            get {
                return ResourceManager.GetString("CommandService_InsertLocalPicture_Open_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert document due to internal error. Please contact us..
        /// </summary>
        internal static string CommandService_PublishCommand_Cannot_convert_document {
            get {
                return ResourceManager.GetString("CommandService_PublishCommand_Cannot_convert_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export because the document has invalid heading orders..
        /// </summary>
        internal static string CommandService_PublishCommand_Cannot_export_because {
            get {
                return ResourceManager.GetString("CommandService_PublishCommand_Cannot_export_because", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Checking.
        /// </summary>
        internal static string CommandService_PublishCommand_Error_Checking {
            get {
                return ResourceManager.GetString("CommandService_PublishCommand_Error_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texxtoor Backup (*.xml, *.txxb) | *.xml; *.txxb | All Files | *.*.
        /// </summary>
        internal static string CommandService_PublishCommand_Texxtoor_Backup {
            get {
                return ResourceManager.GetString("CommandService_PublishCommand_Texxtoor_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Commentare {
            get {
                object obj = ResourceManager.GetObject("Commentare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Subject.
        /// </summary>
        internal static string CommentsTaskPane_btnAddComment_Click_Please_Enter_Subject {
            get {
                return ResourceManager.GetString("CommentsTaskPane_btnAddComment_Click_Please_Enter_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connection.
        /// </summary>
        internal static string CommentsTaskPane_LoadComments_No_Connection {
            get {
                return ResourceManager.GetString("CommentsTaskPane_LoadComments_No_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        internal static string Default_ChapterText {
            get {
                return ResourceManager.GetString("Default_ChapterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class { \n   // code goes here... \n}.
        /// </summary>
        internal static string Default_ListingContent {
            get {
                return ResourceManager.GetString("Default_ListingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string Default_SectionText {
            get {
                return ResourceManager.GetString("Default_SectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to switch document to texxtoor template?
        ///
        ///Currently assigned template is: .
        /// </summary>
        internal static string DocumentService_ApplyTemplate_ {
            get {
                return ResourceManager.GetString("DocumentService_ApplyTemplate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style &apos;{0}&apos; is not allowed. Assign valid style from toolbar.
        /// </summary>
        internal static string DocumentService_AssureStyles_The_style___0___is_not_allowed__Assign_valid_style_from_toolbar {
            get {
                return ResourceManager.GetString("DocumentService_AssureStyles_The_style___0___is_not_allowed__Assign_valid_style_f" +
                        "rom_toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Checking.
        /// </summary>
        internal static string DocumentService_CheckDocument_Error_Checking {
            get {
                return ResourceManager.GetString("DocumentService_CheckDocument_Error_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has been checked successfully..
        /// </summary>
        internal static string DocumentService_CheckDocument_The_document_has_been_checked_successfully_ {
            get {
                return ResourceManager.GetString("DocumentService_CheckDocument_The_document_has_been_checked_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document shall not end here, incomplete sidebar..
        /// </summary>
        internal static string DocumentService_ConsistencyChecker_Document_shall_not_end {
            get {
                return ResourceManager.GetString("DocumentService_ConsistencyChecker_Document_shall_not_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document must begin with a chapter heading.
        /// </summary>
        internal static string DocumentService_ConsistencyChecker_The_document_must_begin_with_a_chapter_heading {
            get {
                return ResourceManager.GetString("DocumentService_ConsistencyChecker_The_document_must_begin_with_a_chapter_heading" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a sidebar that seems to be invalid. Consider creating a new one..
        /// </summary>
        internal static string DocumentService_ConsistencyChecker_There_is_a_sidebar {
            get {
                return ResourceManager.GetString("DocumentService_ConsistencyChecker_There_is_a_sidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deleting.
        /// </summary>
        internal static string DocumentService_DeleteSnippet_Error_Deleting {
            get {
                return ResourceManager.GetString("DocumentService_DeleteSnippet_Error_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete the only chapter heading.
        /// </summary>
        internal static string DocumentService_DeleteSnippet_You_cannot_delete_the_only_chapter_heading {
            get {
                return ResourceManager.GetString("DocumentService_DeleteSnippet_You_cannot_delete_the_only_chapter_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to texxtoor template recognized. Activate full service?.
        /// </summary>
        internal static string DocumentService_DocumentChange_texxtoor_template_recognized__Activate_full_service_ {
            get {
                return ResourceManager.GetString("DocumentService_DocumentChange_texxtoor_template_recognized__Activate_full_servic" +
                        "e_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File Name.
        /// </summary>
        internal static string DocumentService_GetDocumentContent_New_File_Name {
            get {
                return ResourceManager.GetString("DocumentService_GetDocumentContent_New_File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a new document name.\nIt&apos;s not allowed to go with the template&apos;s name..
        /// </summary>
        internal static string DocumentService_GetDocumentContent_You_must_provide_a_new_document_name {
            get {
                return ResourceManager.GetString("DocumentService_GetDocumentContent_You_must_provide_a_new_document_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section violates heading order. The maximum level allowed is &apos;{0}&apos;. Please revisit and check document again..
        /// </summary>
        internal static string DocumentService_HeadingOrderChecker_This_section_violates {
            get {
                return ResourceManager.GetString("DocumentService_HeadingOrderChecker_This_section_violates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure .
        /// </summary>
        internal static string DocumentService_InsertFigure_Figure {
            get {
                return ResourceManager.GetString("DocumentService_InsertFigure_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files (*.jpg, *.jpeg, *.jpe, *.jfif, *.png) | *.jpg; *.jpeg; *.jpe; *.jfif; *.png.
        /// </summary>
        internal static string DocumentService_InsertFigure_Image_files {
            get {
                return ResourceManager.GetString("DocumentService_InsertFigure_Image_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding Index.
        /// </summary>
        internal static string DocumentService_InsertIndex_Error_Adding_Index {
            get {
                return ResourceManager.GetString("DocumentService_InsertIndex_Error_Adding_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the text you wish to add to the Index..
        /// </summary>
        internal static string DocumentService_InsertIndex_Select_the_text {
            get {
                return ResourceManager.GetString("DocumentService_InsertIndex_Select_the_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing .
        /// </summary>
        internal static string DocumentService_InsertListing_Listing {
            get {
                return ResourceManager.GetString("DocumentService_InsertListing_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content goes here....
        /// </summary>
        internal static string DocumentService_InsertSidebar_Content_goes_here___ {
            get {
                return ResourceManager.GetString("DocumentService_InsertSidebar_Content_goes_here___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table .
        /// </summary>
        internal static string DocumentService_InsertTable {
            get {
                return ResourceManager.GetString("DocumentService_InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        internal static string DocumentService_ProvideNewName_Save_File {
            get {
                return ResourceManager.GetString("DocumentService_ProvideNewName_Save_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word files (*.docx, *.doc) | All Files (*.*).
        /// </summary>
        internal static string DocumentService_ProvideNewName_Word_files {
            get {
                return ResourceManager.GetString("DocumentService_ProvideNewName_Word_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap h1 {
            get {
                object obj = ResourceManager.GetObject("h1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap h2 {
            get {
                object obj = ResourceManager.GetObject("h2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap h3 {
            get {
                object obj = ResourceManager.GetObject("h3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap h4 {
            get {
                object obj = ResourceManager.GetObject("h4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap h5 {
            get {
                object obj = ResourceManager.GetObject("h5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding Link.
        /// </summary>
        internal static string InternalLinkTaskPane_btnSave_Click_Error_Adding_Link {
            get {
                return ResourceManager.GetString("InternalLinkTaskPane_btnSave_Click_Error_Adding_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected paragraph is not valid as a link target..
        /// </summary>
        internal static string InternalLinkTaskPane_btnSave_Click_The_selected_paragraph_is_not_valid {
            get {
                return ResourceManager.GetString("InternalLinkTaskPane_btnSave_Click_The_selected_paragraph_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?&lt;type&gt;(Figure)|(Table)|(Listing)?)\s*(?&lt;counter&gt;(?&lt;chapter&gt;\d{1,2}?).(?&lt;number&gt;\d{1,3}?)?)\s*[:]?\s*(?&lt;text&gt;.*?)$.
        /// </summary>
        internal static string InternalLinkTaskPane_CaptionPattern_ {
            get {
                return ResourceManager.GetString("InternalLinkTaskPane_CaptionPattern_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string lb_btn_CharacterCode {
            get {
                return ResourceManager.GetString("lb_btn_CharacterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string lb_btn_CharacterFile {
            get {
                return ResourceManager.GetString("lb_btn_CharacterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keystroke.
        /// </summary>
        internal static string lb_btn_CharacterKeystroke {
            get {
                return ResourceManager.GetString("lb_btn_CharacterKeystroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Template.
        /// </summary>
        internal static string lb_btnActivate {
            get {
                return ResourceManager.GetString("lb_btnActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet List.
        /// </summary>
        internal static string lb_btnBulletList {
            get {
                return ResourceManager.GetString("lb_btnBulletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Document.
        /// </summary>
        internal static string lb_btnCheckDocument {
            get {
                return ResourceManager.GetString("lb_btnCheckDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Document.
        /// </summary>
        internal static string lb_btnCheckDocumentRaw {
            get {
                return ResourceManager.GetString("lb_btnCheckDocumentRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string lb_btnComments {
            get {
                return ResourceManager.GetString("lb_btnComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Text to Table.
        /// </summary>
        internal static string lb_btnConvertTextToTable {
            get {
                return ResourceManager.GetString("lb_btnConvertTextToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string lb_btnCopy {
            get {
                return ResourceManager.GetString("lb_btnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string lb_btnCut {
            get {
                return ResourceManager.GetString("lb_btnCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Snippet.
        /// </summary>
        internal static string lb_btnDelete {
            get {
                return ResourceManager.GetString("lb_btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Table.
        /// </summary>
        internal static string lb_btnDrawTable {
            get {
                return ResourceManager.GetString("lb_btnDrawTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string lb_btnExport {
            get {
                return ResourceManager.GetString("lb_btnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Mode.
        /// </summary>
        internal static string lb_btnFullAddIn {
            get {
                return ResourceManager.GetString("lb_btnFullAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Picture from Local.
        /// </summary>
        internal static string lb_btnGetPicturefromLocal {
            get {
                return ResourceManager.GetString("lb_btnGetPicturefromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Picture from Server.
        /// </summary>
        internal static string lb_btnGetPicturefromServer {
            get {
                return ResourceManager.GetString("lb_btnGetPicturefromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string lb_btnHomePage {
            get {
                return ResourceManager.GetString("lb_btnHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Index Entry.
        /// </summary>
        internal static string lb_btnIndex {
            get {
                return ResourceManager.GetString("lb_btnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        internal static string lb_btnInsertCodeSnippet {
            get {
                return ResourceManager.GetString("lb_btnInsertCodeSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar.
        /// </summary>
        internal static string lb_btnInsertSideBar {
            get {
                return ResourceManager.GetString("lb_btnInsertSideBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table.
        /// </summary>
        internal static string lb_btnInsertTable {
            get {
                return ResourceManager.GetString("lb_btnInsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Text.
        /// </summary>
        internal static string lb_btnInsertText {
            get {
                return ResourceManager.GetString("lb_btnInsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Video.
        /// </summary>
        internal static string lb_btnInsertVideo {
            get {
                return ResourceManager.GetString("lb_btnInsertVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Internal Link.
        /// </summary>
        internal static string lb_btnInternalLink {
            get {
                return ResourceManager.GetString("lb_btnInternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Indent.
        /// </summary>
        internal static string lb_btnLeftIndent {
            get {
                return ResourceManager.GetString("lb_btnLeftIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Text.
        /// </summary>
        internal static string lb_btnMakeText {
            get {
                return ResourceManager.GetString("lb_btnMakeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project.
        /// </summary>
        internal static string lb_btnManageProject {
            get {
                return ResourceManager.GetString("lb_btnManageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbered List.
        /// </summary>
        internal static string lb_btnNumberList {
            get {
                return ResourceManager.GetString("lb_btnNumberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Existing.
        /// </summary>
        internal static string lb_btnOpenExisting {
            get {
                return ResourceManager.GetString("lb_btnOpenExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string lb_btnPaste {
            get {
                return ResourceManager.GetString("lb_btnPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string lb_btnPublish {
            get {
                return ResourceManager.GetString("lb_btnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Server.
        /// </summary>
        internal static string lb_btnPublishRaw {
            get {
                return ResourceManager.GetString("lb_btnPublishRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Tables.
        /// </summary>
        internal static string lb_btnQuickTables {
            get {
                return ResourceManager.GetString("lb_btnQuickTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string lb_btnRedo {
            get {
                return ResourceManager.GetString("lb_btnRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Terms.
        /// </summary>
        internal static string lb_btnRefreshLists {
            get {
                return ResourceManager.GetString("lb_btnRefreshLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Link.
        /// </summary>
        internal static string lb_btnRemoveLink {
            get {
                return ResourceManager.GetString("lb_btnRemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        internal static string lb_btnResearch {
            get {
                return ResourceManager.GetString("lb_btnResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Indent.
        /// </summary>
        internal static string lb_btnRightIndent {
            get {
                return ResourceManager.GetString("lb_btnRightIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Proofing Language.
        /// </summary>
        internal static string lb_btnSetLanguage {
            get {
                return ResourceManager.GetString("lb_btnSetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all index&apos;.
        /// </summary>
        internal static string lb_btnShowIndex {
            get {
                return ResourceManager.GetString("lb_btnShowIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling and Grammar.
        /// </summary>
        internal static string lb_btnSpellingAndGrammar {
            get {
                return ResourceManager.GetString("lb_btnSpellingAndGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        internal static string lb_btnSubscript {
            get {
                return ResourceManager.GetString("lb_btnSubscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        internal static string lb_btnSuperscript {
            get {
                return ResourceManager.GetString("lb_btnSuperscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesaurus.
        /// </summary>
        internal static string lb_btnThesaurus {
            get {
                return ResourceManager.GetString("lb_btnThesaurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string lb_btnUndo {
            get {
                return ResourceManager.GetString("lb_btnUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count.
        /// </summary>
        internal static string lb_btnWordCount {
            get {
                return ResourceManager.GetString("lb_btnWordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string lb_groupStyles {
            get {
                return ResourceManager.GetString("lb_groupStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string lb_grpActivateTexxtoor {
            get {
                return ResourceManager.GetString("lb_grpActivateTexxtoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Text.
        /// </summary>
        internal static string lb_grpBasicText {
            get {
                return ResourceManager.GetString("lb_grpBasicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string lb_grpClipboard {
            get {
                return ResourceManager.GetString("lb_grpClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Interaction.
        /// </summary>
        internal static string lb_grpCommentsPane {
            get {
                return ResourceManager.GetString("lb_grpCommentsPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure.
        /// </summary>
        internal static string lb_grpInsertPicture {
            get {
                return ResourceManager.GetString("lb_grpInsertPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string lb_grpInsertTable {
            get {
                return ResourceManager.GetString("lb_grpInsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string lb_grpInsertText {
            get {
                return ResourceManager.GetString("lb_grpInsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string lb_grpInsertVideo {
            get {
                return ResourceManager.GetString("lb_grpInsertVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string lb_grpInternalLinkPane {
            get {
                return ResourceManager.GetString("lb_grpInternalLinkPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofing.
        /// </summary>
        internal static string lb_grpProofing {
            get {
                return ResourceManager.GetString("lb_grpProofing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic Elements.
        /// </summary>
        internal static string lb_grpSemanticElements {
            get {
                return ResourceManager.GetString("lb_grpSemanticElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic Formats.
        /// </summary>
        internal static string lb_grpSemanticText {
            get {
                return ResourceManager.GetString("lb_grpSemanticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar Type.
        /// </summary>
        internal static string lb_grpSidebarType {
            get {
                return ResourceManager.GetString("lb_grpSidebarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets.
        /// </summary>
        internal static string lb_grpSnippets {
            get {
                return ResourceManager.GetString("lb_grpSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   texxtoor online.
        /// </summary>
        internal static string lb_grpTextoorText {
            get {
                return ResourceManager.GetString("lb_grpTextoorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Id.
        /// </summary>
        internal static string lb_lblDocumentId {
            get {
                return ResourceManager.GetString("lb_lblDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string lb_lblUserName {
            get {
                return ResourceManager.GetString("lb_lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviations.
        /// </summary>
        internal static string lb_menuAbbrevations {
            get {
                return ResourceManager.GetString("lb_menuAbbrevations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cites.
        /// </summary>
        internal static string lb_menuCites {
            get {
                return ResourceManager.GetString("lb_menuCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        internal static string lb_menuDefinitions {
            get {
                return ResourceManager.GetString("lb_menuDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioms.
        /// </summary>
        internal static string lb_menuIdioms {
            get {
                return ResourceManager.GetString("lb_menuIdioms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string lb_menuLinks {
            get {
                return ResourceManager.GetString("lb_menuLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string lb_menuVariables {
            get {
                return ResourceManager.GetString("lb_menuVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lb_mnuSideBarType {
            get {
                return ResourceManager.GetString("lb_mnuSideBarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Styles.
        /// </summary>
        internal static string lb_quickStylesGallery {
            get {
                return ResourceManager.GetString("lb_quickStylesGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string lb_splitbtnConvertSection__btn {
            get {
                return ResourceManager.GetString("lb_splitbtnConvertSection__btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to....
        /// </summary>
        internal static string lb_splitbtnConvertSection__mnu {
            get {
                return ResourceManager.GetString("lb_splitbtnConvertSection__mnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string lb_splitbtnInsertSection__btn {
            get {
                return ResourceManager.GetString("lb_splitbtnInsertSection__btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string lb_splitBtnPicture__btn {
            get {
                return ResourceManager.GetString("lb_splitBtnPicture__btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string lb_splitbtnPublish__btn {
            get {
                return ResourceManager.GetString("lb_splitbtnPublish__btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Options.
        /// </summary>
        internal static string lb_splitbtnPublishRaw__btn {
            get {
                return ResourceManager.GetString("lb_splitbtnPublishRaw__btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Table.
        /// </summary>
        internal static string lb_splitBtnQuickTables__btn {
            get {
                return ResourceManager.GetString("lb_splitBtnQuickTables__btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling.
        /// </summary>
        internal static string lb_splitBtnSpelling__btn {
            get {
                return ResourceManager.GetString("lb_splitBtnSpelling__btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string lb_splitBtnTable__btn {
            get {
                return ResourceManager.GetString("lb_splitBtnTable__btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        internal static string lb_splitBtnTranslate__btn {
            get {
                return ResourceManager.GetString("lb_splitBtnTranslate__btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXXTOOR.
        /// </summary>
        internal static string lb_tabActivateTEXXTOOR {
            get {
                return ResourceManager.GetString("lb_tabActivateTEXXTOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string lb_tabInsert {
            get {
                return ResourceManager.GetString("lb_tabInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic Data.
        /// </summary>
        internal static string lb_tabSemantics {
            get {
                return ResourceManager.GetString("lb_tabSemantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXXTOOR.
        /// </summary>
        internal static string lb_tabTEXXTOOR {
            get {
                return ResourceManager.GetString("lb_tabTEXXTOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Center.
        /// </summary>
        internal static string lb_toggleBtnAlignCenter {
            get {
                return ResourceManager.GetString("lb_toggleBtnAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Left.
        /// </summary>
        internal static string lb_toggleBtnAlignLeft {
            get {
                return ResourceManager.GetString("lb_toggleBtnAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right.
        /// </summary>
        internal static string lb_toggleBtnAlignRight {
            get {
                return ResourceManager.GetString("lb_toggleBtnAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string lb_toggleBtnBold {
            get {
                return ResourceManager.GetString("lb_toggleBtnBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string lb_toggleBtnItalic {
            get {
                return ResourceManager.GetString("lb_toggleBtnItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string lb_toggleBtnUnderline {
            get {
                return ResourceManager.GetString("lb_toggleBtnUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LogOn_btnLogon_Click_Error {
            get {
                return ResourceManager.GetString("LogOn_btnLogon_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response from Server. Please try again..
        /// </summary>
        internal static string LogOn_btnLogon_Click_No_response_from_Server__Please_try_again_ {
            get {
                return ResourceManager.GetString("LogOn_btnLogon_Click_No_response_from_Server__Please_try_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response from Server: .
        /// </summary>
        internal static string LogOn_btnLogon_Click_Response_from_Server__ {
            get {
                return ResourceManager.GetString("LogOn_btnLogon_Click_Response_from_Server__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Normal {
            get {
                object obj = ResourceManager.GetObject("Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments &amp; Meta Data.
        /// </summary>
        internal static string RibbonTexxtoor_GetComments_Comments___Meta_Data {
            get {
                return ResourceManager.GetString("RibbonTexxtoor_GetComments_Comments___Meta_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Links.
        /// </summary>
        internal static string RibbonTexxtoor_InternalLinks_Internal_Links {
            get {
                return ResourceManager.GetString("RibbonTexxtoor_InternalLinks_Internal_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Content.
        /// </summary>
        internal static string RibbonTexxtoor_OnGetGalleryItemCount_No_Content {
            get {
                return ResourceManager.GetString("RibbonTexxtoor_OnGetGalleryItemCount_No_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently selected project does not contain any server images..
        /// </summary>
        internal static string RibbonTexxtoor_OnGetGalleryItemCount_NoCount {
            get {
                return ResourceManager.GetString("RibbonTexxtoor_OnGetGalleryItemCount_NoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed on texxtoor server.
        /// </summary>
        internal static string ServerService_GetDocumentSettings_Login_failed_on_texxtoor_server {
            get {
                return ResourceManager.GetString("ServerService_GetDocumentSettings_Login_failed_on_texxtoor_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing Server.
        /// </summary>
        internal static string ServerService_LogOn_Error_accessing_Server {
            get {
                return ResourceManager.GetString("ServerService_LogOn_Error_accessing_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon at server failed..
        /// </summary>
        internal static string ServerService_LogonFailed {
            get {
                return ResourceManager.GetString("ServerService_LogonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Publishing.
        /// </summary>
        internal static string ServerService_PublishDocument_Error_Publishing {
            get {
                return ResourceManager.GetString("ServerService_PublishDocument_Error_Publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Done.
        /// </summary>
        internal static string ServerService_PublishDocument_Publishing_Done {
            get {
                return ResourceManager.GetString("ServerService_PublishDocument_Publishing_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has been published successfully..
        /// </summary>
        internal static string ServerService_PublishDocument_The_document_has_been_published_successfully_ {
            get {
                return ResourceManager.GetString("ServerService_PublishDocument_The_document_has_been_published_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Headline.
        /// </summary>
        internal static string SidebarCustomDefault {
            get {
                return ResourceManager.GetString("SidebarCustomDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string SidebarNoteDefault {
            get {
                return ResourceManager.GetString("SidebarNoteDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        internal static string SidebarTipDefault {
            get {
                return ResourceManager.GetString("SidebarTipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string SidebarWarningDefault {
            get {
                return ResourceManager.GetString("SidebarWarningDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the texxtoor template to the currently loaded document and activate the texxtoor Add-In..
        /// </summary>
        internal static string st_btnActivate {
            get {
                return ResourceManager.GetString("st_btnActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish the post to the blog account so that other people can read it..
        /// </summary>
        internal static string st_splitbtnPublish__btn {
            get {
                return ResourceManager.GetString("st_splitbtnPublish__btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish the post to the blog account so that other people can read it..
        /// </summary>
        internal static string st_splitbtnPublish__mnu {
            get {
                return ResourceManager.GetString("st_splitbtnPublish__mnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Center.
        /// </summary>
        internal static string st_toggleBtnAlignCenter {
            get {
                return ResourceManager.GetString("st_toggleBtnAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Left.
        /// </summary>
        internal static string st_toggleBtnAlignLeft {
            get {
                return ResourceManager.GetString("st_toggleBtnAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right.
        /// </summary>
        internal static string st_toggleBtnAlignRight {
            get {
                return ResourceManager.GetString("st_toggleBtnAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string st_toggleBtnBold {
            get {
                return ResourceManager.GetString("st_toggleBtnBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string st_toggleBtnItalic {
            get {
                return ResourceManager.GetString("st_toggleBtnItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string st_toggleBtnUnderline {
            get {
                return ResourceManager.GetString("st_toggleBtnUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Text {
            get {
                object obj = ResourceManager.GetObject("Text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
